### ISSUE TITLE
New box created using create_box.sh - gets stuck at "Waiting for SSH to become available..."

### ISSUE THREAD

**Issue by jlegido** [vagrant-libvirt/vagrant-libvirt#1116] opened 2020-05-20 06:52 UTC
### Steps to reproduce

1. Create a VM

```
wget https://vagrantcloud.com/debian/boxes/buster64/versions/10.4.0/providers/libvirt.box'
vim Vagrantfile
```
Content:

```
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.box_url = "file:///libvirt.box"
  config.vm.provider "libvirt"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "acme_"
    # Needed to avoid:
    # Address 192.168.121.0 does not match with network name vagrant-libvirt.
    # I pick an IP in the same range of libvirt network 'vagrant-libvirt'
    # Below IP address if for management, it will NOT be assigned to the VM
    libvirt.management_network_address = '10.151.0.250/24'
  end
end
```
```
vagrant up
```

2. Install any package in the VM, in this example 'git'

```
vagrant ssh
sudo apt-get update && sudo apt-get install -y git
git
sudo shutdown -h now
exit
```

4. Get VM disk location

```
sudo virsh list --all
```

Output:

```
 -    jenkins_node_default   shut off
```

```
sudo virsh edit jenkins_node_default
```

Get the disk part:

```
      <source file='/var/lib/libvirt/images/jenkins_node_default.img'/>
```

3.  Install the tools to create box

```
sudo apt-get update && sudo apt-get install -y git qemu-utils git
git clone https://github.com/vagrant-libvirt/vagrant-libvirt
cd vagrant-libvirt/tools
```

4. Generate the box pointing to the path obtained at step 3. I do it with sudo but you could copy the '.img' file and adjust permissions:

```
sudo ./create_box.sh /var/lib/libvirt/images/jenkins_node_default.img
```

Output:

```
==>   'vagrant box add jenkins_node_default.box --name jenkins_node_default'
```

5. Add the box

```
vagrant box add jenkins_node_default.box --name jenkins_node_default
```

6. Create a VM from that box

```
mkdir /tmp/aux
cd /tmp/aux
vim Vagrantfile
```

Content:

```
Vagrant.configure("2") do |config|
  config.vm.box = "jenkins_node_default"
  config.vm.provider "libvirt"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "jenkins_node_default_vm_"
    # Needed to avoid:
    # Address 192.168.121.0 does not match with network name vagrant-libvirt.
    # I pick an IP in the same range of libvirt network 'vagrant-libvirt'
    # Below IP address if for management, it will NOT be assigned to the VM
    libvirt.management_network_address = '10.151.0.250/24'
  end
end
```
```
vagrant up --debug
```

### Expected behaviour
Recover the prompt and being able to:

```
vagrant ssh
```

### Actual behaviour
It gets stuck at:

```
==> default: Waiting for SSH to become available...
```

### System configuration
**OS/Distro version:**: 

Debian GNU/Linux 10

**Libvirt version:**

libvirtd (libvirt) 5.0.0

**Output of `vagrant version; vagrant plugin list`:** 

```
Installed Version: 2.2.9
Latest Version: 2.2.9
 
You're running an up-to-date version of Vagrant!
vagrant-libvirt (0.1.2, global)
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**

Command:

```
VAGRANT_LOG=debug vagrant up --provider=libvirt
```

The relevant part, which repeats in an infinite loop complains about:

> public/private keypair for the SSH user not being properly set on the guest VM

```
DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not up: #<Vagrant::Errors::SSHAuthenticationFailed: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.>
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Checking key permissions: /root/.vagrant.d/insecure_private_key
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 10.151.0.72
 INFO ssh:   - Port: 22
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/root/.vagrant.d/insecure_private_key"]
DEBUG ssh:   - connect_opts: {:auth_methods=>["none", "hostbased", "publickey"], :config=>false, :forward_agent=>false, :send_env=>false, :keys_only=>true, :verify_host_key=>:never, :password=>nil, :port=>22, :timeout=>15, :user_known_hosts_file=>[], :verbose=>:debug, :logger=>#<Logger:0x00007f2d28ed1c08 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007f2d28ed1b90 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00007f2d28ed1a00 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<StringIO:0x00007f2d28ed1c58>, @mon_mutex=#<Thread::Mutex:0x00007f2d28ed1988>, @mon_mutex_owner_object_id=69915968441600, @mon_owner=nil, @mon_count=0>>, :keys=>["/root/.vagrant.d/insecure_private_key"], :remote_user=>"vagrant"}
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2020-05-20T08:30:06.755336 #967] DEBUG -- net.ssh.transport.session[3f9694775b68]: establishing connection to 10.151.0.72:22
D, [2020-05-20T08:30:06.756088 #967] DEBUG -- net.ssh.transport.session[3f9694775b68]: connection established
I, [2020-05-20T08:30:06.756268 #967]  INFO -- net.ssh.transport.server_version[3f9694775064]: negotiating protocol version
D, [2020-05-20T08:30:06.756338 #967] DEBUG -- net.ssh.transport.server_version[3f9694775064]: local is `SSH-2.0-Ruby/Net::SSH_5.2.0 x86_64-linux'
D, [2020-05-20T08:30:06.771213 #967] DEBUG -- net.ssh.transport.server_version[3f9694775064]: remote is `SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2'
I, [2020-05-20T08:30:06.771936 #967]  INFO -- net.ssh.transport.algorithms[3f96947f0fd4]: sending KEXINIT
D, [2020-05-20T08:30:06.772524 #967] DEBUG -- socket[3f9694775898]: queueing packet nr 0 type 20 len 1324
D, [2020-05-20T08:30:06.772701 #967] DEBUG -- socket[3f9694775898]: sent 1328 bytes
D, [2020-05-20T08:30:06.772897 #967] DEBUG -- socket[3f9694775898]: read 1080 bytes
D, [2020-05-20T08:30:06.773145 #967] DEBUG -- socket[3f9694775898]: received packet nr 0 type 20 len 1076
I, [2020-05-20T08:30:06.773269 #967]  INFO -- net.ssh.transport.algorithms[3f96947f0fd4]: got KEXINIT from server
I, [2020-05-20T08:30:06.773726 #967]  INFO -- net.ssh.transport.algorithms[3f96947f0fd4]: negotiating algorithms
D, [2020-05-20T08:30:06.774095 #967] DEBUG -- net.ssh.transport.algorithms[3f96947f0fd4]: negotiated:
* kex: ecdh-sha2-nistp521
* host_key: ssh-ed25519
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-512
* hmac_server: hmac-sha2-512
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2020-05-20T08:30:06.774182 #967] DEBUG -- net.ssh.transport.algorithms[3f96947f0fd4]: exchanging keys
D, [2020-05-20T08:30:06.784865 #967] DEBUG -- socket[3f9694775898]: queueing packet nr 1 type 30 len 148
D, [2020-05-20T08:30:06.784943 #967] DEBUG -- socket[3f9694775898]: sent 152 bytes
D, [2020-05-20T08:30:06.822066 #967] DEBUG -- socket[3f9694775898]: read 312 bytes
D, [2020-05-20T08:30:06.822238 #967] DEBUG -- socket[3f9694775898]: received packet nr 1 type 31 len 292
D, [2020-05-20T08:30:06.830116 #967] DEBUG -- socket[3f9694775898]: queueing packet nr 2 type 21 len 20
D, [2020-05-20T08:30:06.830217 #967] DEBUG -- socket[3f9694775898]: sent 24 bytes
D, [2020-05-20T08:30:06.830368 #967] DEBUG -- socket[3f9694775898]: received packet nr 2 type 21 len 12
D, [2020-05-20T08:30:06.830864 #967] DEBUG -- net.ssh.authentication.session[3f969481b2fc]: beginning authentication of `vagrant'
D, [2020-05-20T08:30:06.831062 #967] DEBUG -- socket[3f9694775898]: queueing packet nr 3 type 5 len 28
D, [2020-05-20T08:30:06.831137 #967] DEBUG -- socket[3f9694775898]: sent 96 bytes
D, [2020-05-20T08:30:06.874865 #967] DEBUG -- socket[3f9694775898]: read 96 bytes
D, [2020-05-20T08:30:06.875141 #967] DEBUG -- socket[3f9694775898]: received packet nr 3 type 6 len 28
D, [2020-05-20T08:30:06.875339 #967] DEBUG -- net.ssh.authentication.session[3f969481b2fc]: trying none
D, [2020-05-20T08:30:06.875723 #967] DEBUG -- socket[3f9694775898]: queueing packet nr 4 type 50 len 44
D, [2020-05-20T08:30:06.875865 #967] DEBUG -- socket[3f9694775898]: sent 112 bytes
D, [2020-05-20T08:30:06.882261 #967] DEBUG -- socket[3f9694775898]: read 96 bytes
D, [2020-05-20T08:30:06.882529 #967] DEBUG -- socket[3f9694775898]: received packet nr 4 type 51 len 28
D, [2020-05-20T08:30:06.882689 #967] DEBUG -- net.ssh.authentication.session[3f969481b2fc]: allowed methods: publickey
D, [2020-05-20T08:30:06.882823 #967] DEBUG -- net.ssh.authentication.methods.none[3f969481a078]: none failed
D, [2020-05-20T08:30:06.882954 #967] DEBUG -- net.ssh.authentication.session[3f969481b2fc]: trying publickey
D, [2020-05-20T08:30:06.883511 #967] DEBUG -- net.ssh.authentication.agent[3f9694826558]: connecting to ssh-agent
E, [2020-05-20T08:30:06.883637 #967] ERROR -- net.ssh.authentication.agent[3f9694826558]: could not connect to ssh-agent: Agent not configured
D, [2020-05-20T08:30:06.884046 #967] DEBUG -- net.ssh.authentication.methods.publickey[3f9694826a80]: trying publickey (dd:3b:b8:2e:85:04:06:e9:ab:ff:a8:0a:c0:04:6e:d6)
D, [2020-05-20T08:30:06.884452 #967] DEBUG -- socket[3f9694775898]: queueing packet nr 5 type 50 len 348
D, [2020-05-20T08:30:06.884600 #967] DEBUG -- socket[3f9694775898]: sent 416 bytes
D, [2020-05-20T08:30:06.890960 #967] DEBUG -- socket[3f9694775898]: read 96 bytes
D, [2020-05-20T08:30:06.891205 #967] DEBUG -- socket[3f9694775898]: received packet nr 5 type 51 len 28
D, [2020-05-20T08:30:06.891344 #967] DEBUG -- net.ssh.authentication.session[3f969481b2fc]: allowed methods: publickey
E, [2020-05-20T08:30:06.891426 #967] ERROR -- net.ssh.authentication.session[3f969481b2fc]: all authorization methods failed (tried none, publickey)

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not up: #<Vagrant::Errors::SSHAuthenticationFailed: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.>
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Checking key permissions: /root/.vagrant.d/insecure_private_key
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 10.151.0.72
 INFO ssh:   - Port: 22
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/root/.vagrant.d/insecure_private_key"]
DEBUG ssh:   - connect_opts: {:auth_methods=>["none", "hostbased", "publickey"], :config=>false, :forward_agent=>false, :send_env=>false, :keys_only=>true, :verify_host_key=>:never, :password=>nil, :port=>22, :timeout=>15, :user_known_hosts_file=>[], :verbose=>:debug, :logger=>#<Logger:0x00000000032638a8 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x0000000003263448 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00000000032630b0 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<StringIO:0x0000000003263c18>, @mon_mutex=#<Thread::Mutex:0x0000000003262cf0>, @mon_mutex_owner_object_id=26417240, @mon_owner=nil, @mon_count=0>>, :keys=>["/root/.vagrant.d/insecure_private_key"], :remote_user=>"vagrant"}
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.box = "jenkins_node_default"
  config.vm.provider "libvirt"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "jenkins_node_default_vm_"
    # Needed to avoid:
    # Address 192.168.121.0 does not match with network name vagrant-libvirt.
    # I pick an IP in the same range of libvirt network 'vagrant-libvirt'
    # Below IP address if for management, it will NOT be assigned to the VM
    libvirt.management_network_address = '10.151.0.250/24'
  end
end
```

**Are you using upstream vagrant package or your distros package?**
No

**Comment by jlegido** [comment] 2020-05-20 09:39
By the way many thanks to all the people involved in this project for their time.

**Comment by sjurado** [comment] 2020-05-24 01:27
You need to change vagrant-libvirt network using virsh to make it work.  Backup your config first:

`/etc/libvirt/qemu/networks/vagrant-libvirt.xml`

In theory you should be able to update it with a simple `virsh net-edit vagrant-libvirt` but it never worked for me. So I had to delete the config and recreate it:

```
virsh net-destroy vagrant-libvirt
virsh net-undefine vagrant-libvirt
```
Copy that vagrant-libvirt.xml to the same folder with the new network you are using and:

```
virsh net-define /etc/libvirt/qemu/networks/vagrant-libvirt.xml
virsh net-start vagrant-libvirt
```

**Comment by jlegido** [comment] 2020-05-26 05:27
@sjurado many thanks for the detailed workaround provided, I will test it as soon as possible and document the result here.

Should I understand then that you was able to reproduce the same behaviour?

If yes, I think this issue should be accepted as a bug and treated accordingly.

Again many thanks.

**Comment by electrofelix** [comment] 2020-05-26 08:59
@jlegido so the network management address issue you've encountered is because at some point you've created a VM with vagrant-libvirt and the management address was set to something other than the default. Once a network is created we don't try and remove them to replace if there is a mismatch between the name and the address. The suggestion by @sjurado is the correct fix for this. The alternative if for some reason you can't use the default management address is to create `~/.vagrant.d/Vagrantfile` with the following contents:
```
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    # Needed to avoid:
    # Address 192.168.121.0 does not match with network name vagrant-libvirt.
    # I pick an IP in the same range of libvirt network 'vagrant-libvirt'
    # Below IP address if for management, it will NOT be assigned to the VM
    libvirt.management_network_address = '10.151.0.250/24'
  end
end
```

This will be picked up by all vagrant operations and merged with the one under the current directly to apply always. Essentially it's a file to apply global default settings when needed.

Back to the second problem, the error you are seeing is from vagrant itself rather than vagrant-libvirt. At this point you can see the log messages contain `INFO ssh:   - Host: 10.151.0.72`. This means the machine has been assigned an IP address.

However the problem is that vagrant is unable to connect using the insecure ssh key for the initial connection before replacing it with a unique key.

The output contains the following message:
```
This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well
```

When you initially created the VM, the insecure key would have been removed to prevent it from being used subsequently once the first successful SSH connection is made. In order to package a machine as a vagrant box you'll need to re-add it back to the machine to replace the generated key that was inserted.

So the steps:
```
vagrant ssh
sudo apt-get update && sudo apt-get install -y git
git
sudo shutdown -h now
exit
```
Should become:
```
vagrant ssh
sudo apt-get update && sudo apt-get install -y git
git
<inject vagrant ssh public key>
sudo shutdown -h now
exit
```
You should be able to use ssh-copy-id from the host at that point with the various settings from `vagrant ssh-config`.

There is a copy of the public key available in the vagrant installation via:
```
ls /opt/vagrant/embedded/gems/*/gems/vagrant-*/keys/vagrant.pub
```

**Comment by jlegido** [comment] 2020-05-28 10:25
@electrofelix many thanks for your reply.

I will paste here the commands that I followed, still stuck at the same step and I guess for the same reason.

I took out the custom network, to remove some noise.

```
vim Vagrantfile
```

Content:

```
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "libvirt"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "acme_"
  end
end
```

```
vagrant up

vagrant ssh

sudo apt-get update && sudo apt-get install -y git
git
exit

vagrant ssh-config
```

Output:

```
Host default
  HostName 192.168.121.8
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/usuario/vagrant/.vagrant/machines/default/libvirt/private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

```
ls /opt/vagrant/embedded/gems/*/gems/vagrant-*/keys/vagrant.pub
```

Output:


```
/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/keys/vagrant.pub
```

```
scp -i /home/usuario/vagrant/.vagrant/machines/default/libvirt/private_key /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/keys/vagrant.pub vagrant@192.168.121.8:~/.ssh/authorized_keys
```

```
vagrant halt

sudo virsh list --all

sudo virsh edit acme_default
```

Get the disk path:

```
      <source file='/var/lib/libvirt/images/acme_default.img'/>
```

```
sudo apt-get update && sudo apt-get install -y git qemu-utils git

git clone https://github.com/vagrant-libvirt/vagrant-libvirt

cd vagrant-libvirt/tools

sudo ./create_box.sh /var/lib/libvirt/images/acme_default.img

vagrant box add acme_default.box --name acme_default

mkdir /tmp/aux

cd /tmp/aux

vim Vagrantfile
```

Content:

```
Vagrant.configure("2") do |config|
  config.vm.box = "acme_default"
  config.vm.provider "libvirt"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "acme_default_vm_"
  end
end
```

```
VAGRANT_LOG=debug vagrant up --provider=libvirt
```

Stuck, similar output:

```
DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not up: #<Vagrant::Errors::SSHAuthenticationFailed: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.>
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Checking key permissions: /home/usuario/.vagrant.d/insecure_private_key
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 192.168.121.160
 INFO ssh:   - Port: 22
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/home/usuario/.vagrant.d/insecure_private_key"]
DEBUG ssh:   - connect_opts: {:auth_methods=>["none", "hostbased", "publickey"], :config=>false, :forward_agent=>false, :send_env=>false, :keys_only=>true, :verify_host_key=>:never, :password=>nil, :port=>22, :timeout=>15, :user_known_hosts_file=>[], :verbose=>:debug, :logger=>#<Logger:0x00007f9658c9df60 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007f9658c9df10 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00007f9658c9dec0 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<StringIO:0x00007f9658c9e000>, @mon_mutex=#<Thread::Mutex:0x00007f9658c9de48>, @mon_mutex_owner_object_id=70141855723360, @mon_owner=nil, @mon_count=0>>, :keys=>["/home/usuario/.vagrant.d/insecure_private_key"], :remote_user=>"vagrant"}
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2020-05-28T12:09:42.341447 #2740424] DEBUG -- net.ssh.transport.session[3fcb2c65aef0]: establishing connection to 192.168.121.160:22
D, [2020-05-28T12:09:42.341797 #2740424] DEBUG -- net.ssh.transport.session[3fcb2c65aef0]: connection established
I, [2020-05-28T12:09:42.341890 #2740424]  INFO -- net.ssh.transport.server_version[3fcb2c65a75c]: negotiating protocol version
D, [2020-05-28T12:09:42.341926 #2740424] DEBUG -- net.ssh.transport.server_version[3fcb2c65a75c]: local is `SSH-2.0-Ruby/Net::SSH_5.2.0 x86_64-linux'
D, [2020-05-28T12:09:42.348582 #2740424] DEBUG -- net.ssh.transport.server_version[3fcb2c65a75c]: remote is `SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2'
I, [2020-05-28T12:09:42.348849 #2740424]  INFO -- net.ssh.transport.algorithms[3fcb2c66b764]: sending KEXINIT
D, [2020-05-28T12:09:42.349092 #2740424] DEBUG -- socket[3fcb2c65ac0c]: queueing packet nr 0 type 20 len 1324
D, [2020-05-28T12:09:42.349174 #2740424] DEBUG -- socket[3fcb2c65ac0c]: sent 1328 bytes
D, [2020-05-28T12:09:42.349259 #2740424] DEBUG -- socket[3fcb2c65ac0c]: read 1080 bytes
D, [2020-05-28T12:09:42.349368 #2740424] DEBUG -- socket[3fcb2c65ac0c]: received packet nr 0 type 20 len 1076
I, [2020-05-28T12:09:42.349422 #2740424]  INFO -- net.ssh.transport.algorithms[3fcb2c66b764]: got KEXINIT from server
I, [2020-05-28T12:09:42.349574 #2740424]  INFO -- net.ssh.transport.algorithms[3fcb2c66b764]: negotiating algorithms
D, [2020-05-28T12:09:42.349714 #2740424] DEBUG -- net.ssh.transport.algorithms[3fcb2c66b764]: negotiated:
* kex: ecdh-sha2-nistp521
* host_key: ssh-ed25519
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-512
* hmac_server: hmac-sha2-512
* compression_client: none
* compression_server: none
* language_client:
* language_server:
D, [2020-05-28T12:09:42.349752 #2740424] DEBUG -- net.ssh.transport.algorithms[3fcb2c66b764]: exchanging keys
D, [2020-05-28T12:09:42.353237 #2740424] DEBUG -- socket[3fcb2c65ac0c]: queueing packet nr 1 type 30 len 148
D, [2020-05-28T12:09:42.353281 #2740424] DEBUG -- socket[3fcb2c65ac0c]: sent 152 bytes
D, [2020-05-28T12:09:42.393129 #2740424] DEBUG -- socket[3fcb2c65ac0c]: read 312 bytes
D, [2020-05-28T12:09:42.393241 #2740424] DEBUG -- socket[3fcb2c65ac0c]: received packet nr 1 type 31 len 292
D, [2020-05-28T12:09:42.396535 #2740424] DEBUG -- socket[3fcb2c65ac0c]: queueing packet nr 2 type 21 len 20
D, [2020-05-28T12:09:42.396597 #2740424] DEBUG -- socket[3fcb2c65ac0c]: sent 24 bytes
D, [2020-05-28T12:09:42.396664 #2740424] DEBUG -- socket[3fcb2c65ac0c]: received packet nr 2 type 21 len 12
D, [2020-05-28T12:09:42.396914 #2740424] DEBUG -- net.ssh.authentication.session[3fcb2c694ce0]: beginning authentication of `vagrant'
D, [2020-05-28T12:09:42.397013 #2740424] DEBUG -- socket[3fcb2c65ac0c]: queueing packet nr 3 type 5 len 28
D, [2020-05-28T12:09:42.397047 #2740424] DEBUG -- socket[3fcb2c65ac0c]: sent 96 bytes
D, [2020-05-28T12:09:42.438991 #2740424] DEBUG -- socket[3fcb2c65ac0c]: read 96 bytes
D, [2020-05-28T12:09:42.439144 #2740424] DEBUG -- socket[3fcb2c65ac0c]: received packet nr 3 type 6 len 28
D, [2020-05-28T12:09:42.439237 #2740424] DEBUG -- net.ssh.authentication.session[3fcb2c694ce0]: trying none
D, [2020-05-28T12:09:42.439364 #2740424] DEBUG -- socket[3fcb2c65ac0c]: queueing packet nr 4 type 50 len 44
D, [2020-05-28T12:09:42.439414 #2740424] DEBUG -- socket[3fcb2c65ac0c]: sent 112 bytes
D, [2020-05-28T12:09:42.449023 #2740424] DEBUG -- socket[3fcb2c65ac0c]: read 96 bytes
D, [2020-05-28T12:09:42.449165 #2740424] DEBUG -- socket[3fcb2c65ac0c]: received packet nr 4 type 51 len 28
D, [2020-05-28T12:09:42.449231 #2740424] DEBUG -- net.ssh.authentication.session[3fcb2c694ce0]: allowed methods: publickey
D, [2020-05-28T12:09:42.449287 #2740424] DEBUG -- net.ssh.authentication.methods.none[3fcb2c6a30ec]: none failed
D, [2020-05-28T12:09:42.449336 #2740424] DEBUG -- net.ssh.authentication.session[3fcb2c694ce0]: trying publickey
D, [2020-05-28T12:09:42.449543 #2740424] DEBUG -- net.ssh.authentication.agent[3fcb2c6b1430]: connecting to ssh-agent
E, [2020-05-28T12:09:42.449587 #2740424] ERROR -- net.ssh.authentication.agent[3fcb2c6b1430]: could not connect to ssh-agent: Agent not configured
D, [2020-05-28T12:09:42.449723 #2740424] DEBUG -- net.ssh.authentication.methods.publickey[3fcb2c6b16d8]: trying publickey (dd:3b:b8:2e:85:04:06:e9:ab:ff:a8:0a:c0:04:6e:d6)
D, [2020-05-28T12:09:42.449862 #2740424] DEBUG -- socket[3fcb2c65ac0c]: queueing packet nr 5 type 50 len 348
D, [2020-05-28T12:09:42.449916 #2740424] DEBUG -- socket[3fcb2c65ac0c]: sent 416 bytes
D, [2020-05-28T12:09:42.459490 #2740424] DEBUG -- socket[3fcb2c65ac0c]: read 96 bytes
D, [2020-05-28T12:09:42.459637 #2740424] DEBUG -- socket[3fcb2c65ac0c]: received packet nr 5 type 51 len 28
D, [2020-05-28T12:09:42.459704 #2740424] DEBUG -- net.ssh.authentication.session[3fcb2c694ce0]: allowed methods: publickey
E, [2020-05-28T12:09:42.459738 #2740424] ERROR -- net.ssh.authentication.session[3fcb2c694ce0]: all authorization methods failed (tried none, publickey)

DEBUG ssh: == Net-SSH connection debug-level log END ==
```

The private key is the same:

```
diff /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/keys/vagrant /home/usuario/.vagrant.d/insecure_private_key
```

**Comment by electrofelix** [comment] 2020-05-28 12:51
@jlegido maybe have a second terminal open with a connection into the initial VM running and inspect the result of the scp, as that may not be working as expected. I tried the same commands as you and the machine came up correctly for me, though I was running all the steps as a normal user beside the script to create the box.

It should be possible to confirm you can still ssh into the vm using the insecure private key after you replace the key in the VM with the scp, though if it's broken having the ssh connection in a second terminal will likely make it easier to debug.

```
ssh -i /home/usuario/.vagrant.d/insecure_private_key -o UserKnownHostsFile=/dev/null -o UserKnownHostsFile=no vagrant@<ip>
```

**Comment by jlegido** [comment] 2020-05-28 14:35
I was finally able to solve it.

Additional evidences:

* With the hack of copying again the public key (located in '/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/keys/vagrant.pub') even though the second 'vagrant up' command gets stuck in the infinite loop with the wrong SSH keys, if interrupted with 'CTRL + C' the VM is in running state, so you can 'virsh console' to it
* The root cause of my issue (which with due respect I still consider a bug) is that after second 'vagrant up' the '/home/vagrant/.ssh/authorized_keys' changed, and it contains another public key

Solution:

Superlong, I will copy/paste again all the commands:

```
vim Vagrantfile
```

Content:

```
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "libvirt"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "acme_"
  end
end
```

```
vagrant up

vagrant ssh

sudo apt-get update && sudo apt-get install -y git
git
exit

vagrant ssh-config
```

Output:

```
Host default
  HostName 192.168.121.8
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/usuario/vagrant/.vagrant/machines/default/libvirt/private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

```
ls /opt/vagrant/embedded/gems/*/gems/vagrant-*/keys/vagrant.pub
```

Output:


```
/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/keys/vagrant.pub
```

**Here comes the main difference**:

```
scp -i /home/usuario/vagrant/.vagrant/machines/default/libvirt/private_key /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/keys/vagrant.pub vagrant@192.168.121.8:~/
vagrant ssh
cat vagrant.pub .ssh/authorized_keys
sudo shutdown -h
```

```
sudo virsh list --all

sudo virsh edit acme_default
```

Get the disk path:

```
      <source file='/var/lib/libvirt/images/acme_default.img'/>
```

```
sudo apt-get update && sudo apt-get install -y git qemu-utils git

git clone https://github.com/vagrant-libvirt/vagrant-libvirt

cd vagrant-libvirt/tools

sudo ./create_box.sh /var/lib/libvirt/images/acme_default.img

vagrant box add acme_default.box --name acme_default

mkdir /tmp/aux

cd /tmp/aux

vim Vagrantfile
```

Content:

```
Vagrant.configure("2") do |config|
  config.vm.box = "acme_default"
  config.vm.provider "libvirt"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "acme_default_vm_"
  end
end
```

```
VAGRANT_LOG=debug vagrant up --provider=libvirt
```

Open a new console

Console to the running VM:

```
sudo virsh console acme_default_vm_default
```

Press 'Enter'

Type 'root' and press 'Enter'

Install and editor:

```
sudo aptitude update && sudo aptitude install -y vim
```

Edit the file:

```
vim /home/vagrant/.ssh/authorized_keys
```

With the same content of '/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/keys/vagrant.pub'

Once you save and exit.... the stuck process (running in the other tab) finishes, and after that:

* You can 'vagrant ssh'
* The file '/home/vagrant/.ssh/authorized_keys' now contains 2 keys

I will refine the process a little bit, but I thinks this should be accepted as a bug.

Many many thanks @electrofelix for your help and your time.

**Comment by jlegido** [comment] 2020-05-28 17:55
Now I was able to execute all the procedure without having to 'virsh console' to manually change the public key.

**Comment by electrofelix** [comment] 2020-11-16 18:14
@jlegido so I've re-read the Vagrant documentation as I realised I missed a much simpler fix. If you are looking to package up a VM that was created with Vagrant, should just set `config.ssh.insert_key = false` to your Vagrantfile to disable the replacement of the default ssh key.

I forgot about this setting at https://www.vagrantup.com/docs/vagrantfile/ssh_settings#config-ssh-insert_key

Setting that means the ssh key doesn't get replaced and after packaging up and creating a new machine from the exported box, you should be able to connect.

I'll update the readme's and the tool usage to try and help flag this.

**Comment by jlegido** [comment] 2020-11-17 08:46
@electrofelix many thanks for tour time and for having a look to this issue.

I will repeat the test with the proposed flag and post my result in this ticket, I will need some days probably.

Thanks again

**Closed** 2020-11-17 19:31 UTC
