### ISSUE TITLE
CPU topology not being set properly

### ISSUE THREAD

**Issue by crushten** [vagrant-libvirt/vagrant-libvirt#975] opened 2019-02-17 22:08 UTC
### Steps to reproduce
1. Make sure `vagrant`, `libvirt`, and `vagrant-libvirt` are installed and working.
2. Configure vm `cpus` and `cputopology`.
3. Set vm `cpu_mode` to `host-passthrough`.

Please let me know if you need anything else.

### Expected behavior
Virtual machines should report correct topology.   Does not seem to be an issue with `virt-install`.

### Actual behavior
The topology is not set in the xml file when 'host-passthrough` is defined.  So the guest reports as having 4 sockets with 1 cpu and 1 core each.  It should be 1 cpu in 1 socket with 4 cores.  I have tried with different topology configurations but that didnt matter since it is not being set in the xml file.  This is the same issue I have on my workstation as well (Dual Intel Sandy Bridge Xeons).

Snippet from vm (running on desktop):
```
[vagrant@cputest1 ~]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz
Stepping:              3
CPU MHz:               3504.000
BogoMIPS:              7008.00
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 arat umip spec_ctrl
```
snippet from xml (running on desktop)
```
 <domain type='kvm'>
  <name>hostspassthrough_cputest1</name>
  <uuid>c636f68e-9407-47b8-8e72-188cc8138024</uuid>
  <memory unit='KiB'>524288</memory>
  <currentMemory unit='KiB'>524288</currentMemory>
  <vcpu placement='static'>4</vcpu>
  <os>
    <type arch='x86_64' machine='pc-i440fx-3.1'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <cpu mode='host-passthrough' check='none'/>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
...
```
No 'host-passthrough'

Snippet from Vagrantfile
```
  config.vm.provider :libvirt do |virt|
    virt.driver = "kvm"
    virt.memory = "512"
    virt.cpus = "4"
    virt.cputopology :sockets => '1', :cores => '4', :threads => '1'
    #virt.cpu_mode = 'host-passthrough'
  end
```
snippet from vm (running on desktop) Cores and sockets are set correctly when cpu mode is not 'host-passthrough'.
```
[vagrant@cputest1 ~]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel Core Processor (Skylake, IBRS)
Stepping:              3
CPU MHz:               3504.000
BogoMIPS:              7008.00
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 arat umip spec_ctrl
```
snippet from xml (running on desktop) cpu topology is now present in xml when cpu is not set to 'host-passthrough'.
```

<domain type='kvm'>
  <name>hostspassthrough_cputest1</name>
  <uuid>1caaa4be-f35a-4158-815d-d8088e11644b</uuid>
  <memory unit='KiB'>524288</memory>
  <currentMemory unit='KiB'>524288</currentMemory>
  <vcpu placement='static'>4</vcpu>
  <os>
    <type arch='x86_64' machine='pc-i440fx-3.1'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <cpu mode='host-model' check='partial'>
    <model fallback='allow'/>
    <topology sockets='1' cores='4' threads='1'/>
  </cpu>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
```

### System configuration
**OS/Distro version:**: Arch Linux

**Libvirt version:**5.0.0.1

**Output of `vagrant version; vagrant plugin list`:**
vagrant version -> 2.2.3
vagrant plugin list -> 
```
fog (1.38.0, global)
  - Version Constraint: > 0
sahara (0.0.17, global)
  - Version Constraint: > 0
vagrant-hostsupdater (1.1.1.160, global)
  - Version Constraint: > 0
vagrant-libvirt (0.0.45, global)
  - Version Constraint: > 0
vagrant-scp (0.5.7, global)
  - Version Constraint: > 0
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
VAGRANT_LOG=debug vagrant up &> vagrant-libvirt_hostpassthrough_debug

https://gist.github.com/crushten/60c7ee48d3a2564fb88aac6082809919
```
**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

######################################################################
#
# Launch a set of servers to mimick an environment for deployment
#
######################################################################

require_relative 'vagrant/key_authorization.rb'

Vagrant.configure("2") do |config|

  config.vm.box = "centos/6"

  authorize_key_for_root(config, '~/.ssh/id_rsa_vagrant.pub')

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

  config.vm.provider :libvirt do |virt|
    virt.driver = "kvm"
    virt.memory = "512"
    virt.cpus = "4"
    virt.cputopology :sockets => '1', :cores => '4', :threads => '1'
    virt.cpu_mode = 'host-passthrough'
  end


  # stop sharing our project directory
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true


  ##############################################
  #
  # Servers
  #
  ##############################################
  [

    [:cputest1,   '192.168.77.152', 'centos/7'],
    [:cputest2,   '192.168.77.161', 'generic/ubuntu1804'],
  ].each do |(name, ip, box, memory)|
    config.vm.define(name) do |host|
      host.vm.box = box
      host.vm.network :private_network, ip: ip
      host.vm.hostname = "#{name}.stack.test"
      memory ||= '512'
      config.vm.provider :libvirt do |virt|
        virt.memory = memory
      end
    end # end config
  end # end servers loop

end# end main

```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by nksCH** [comment] 2020-06-14 18:52
Seeing exactly the same behaviour.
```
# vagrant version
Installed Version: 2.2.7
```

**Comment by mmguero** [comment] 2021-12-07 20:52
I see the same issue with  `host-model` regardless of what I set for `cpus` and `cputopology`.

```
    libvirt.cpu_mode = 'host-model'
    libvirt.cpus = 8
    libvirt.cputopology :sockets => '4', :cores => '2', :threads => '1'
```

**Comment by electrofelix** [comment] 2021-12-08 19:47
@crushten sorry for the delay, hadn't popped onto my radar until now.

It looks like this is caused by the template assuming that pass-through mode doesn't support being able to either modify the cpu features or set the topology:
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/87ec540994c6dd6c2f51d18367ba483e56ebe481/lib/vagrant-libvirt/templates/domain.xml.erb#L9-L26

@mmguero that sounds like a different issue, I think you'll need to go through the steps to generate a debug log as the cause of this issue is that the if the mode is set to `'host-passthrough'` a number of options are skipped, but this is not done when `'host-model'` is used. When I check locally whether when host-model is set that it gets reported correctly in the guest, it appears to work as expected. Possibly you need the latest code (the fix for this issue has no impact).

**Closed** 2021-12-08 19:48 UTC

**Comment by crushten** [comment] 2021-12-09 03:14
Thanks for the fix!
