### ISSUE TITLE
Cannot assign static IP on a debian/jessie64/stretch64 using libvirt provider 

### ISSUE THREAD

**Issue by Aurelien-** [vagrant-libvirt/vagrant-libvirt#867] opened 2018-02-21 07:44 UTC
Hello,

I am not able to set a static IP with : 

> config.vm.network "private_network", ip: "XXX.XXX.XXX.XXX"

System config :

> Ubuntu 16.04, 4.13.0-32-generic
> Vagrant 2.0.2 (installed from deb package)
> libvirtd (libvirt) 1.3.1

Vagrant libvirt plugin installed with command :

> vagrant plugin install vagrant-libvirt

vagrant plugin list :

> vagrant-libvirt (0.0.43)
> virtualbox (0.8.6)

Guest systems tried : 

> 
> debian/jessie64 and debian/stretch64
> 
### Vagrantfile

> Vagrant.configure("2") do |config|
>     config.vm.box = "debian/stretch64"
>     config.vm.provider "libvirt"
> 
>     config.vm.synced_folder ".", "/vagrant", :nfs => true, :mount_options => ['rw', 'vers=3', 'tcp']
>  
>     config.vm.provider "libvirt" do |v|
>         v.memory = 4096
>         v.cpus = 1
>     end
> 
>     # Basic setup through a shell provisioner
>     config.vm.provision "shell", inline: <<-SHELL
>       apt-get update
>       apt-get upgrade -y
>       apt-get install -y net-tools htop apt-transport-https curl iftop
>     SHELL
> 
> 
>       (1..1).each do |i|
>           config.vm.define "test-#{i}" do |node|
>              node.vm.network "private_network", ip: "192.168.50.#{i+1}"
>              node.vm.hostname = "test-#{i}"
>           end
>       end  
> end

### Debug output
https://gist.github.com/Aurelien-/37d17bb3bfc43c36d11af248663d9e6d

### Expected behavior
sudo ifconfig should return 192.168.50.2 for ens6 interface

### Actual behavior
sudo ifconfig returns random address in subnet 192.168.50.0 for ens6 interface. Almost surely obtained by DHCP.

### Steps to reproduce
1. Use provided Vagranfile in this issue
2. vagrant up --provider=libvirt

I am able to force the ip with the following provisioning lines, but only after the second boot (`vagrant halt; vagrant up`) : 

> node.vm.provision "shell", inline: "echo \'[Match]
> Name=ens6
> 
> [Network]
> DHCP=yes
> Address=192.168.50.#{i+1}\' > /etc/systemd/network/98-ens6.network"

This has been also tested on a debian/jessie64 box with same results (no static ip, forced with the provisiong shell script).

**Comment by sourceindex** [comment] 2018-03-06 08:18
Im experiencing the same issue

## Version Info

```
vagrant --version
Vagrant 2.0.2
```

```
vagrant plugin list
vagrant-libvirt (0.0.43)
```

## Steps to reproduce
```
cd vagrant-libvirt/example_box
grep -v -e ^$ -e # Vagrantfile                                                                                  
Vagrant.configure("2") do |config|
  config.vm.define :test_vm do |test_vm|
    test_vm.vm.box = "debian/stretch64"
    test_vm.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
    end
    test_vm.vm.network :private_network, :ip => '10.20.30.40'
  end
end
```

```
vagrant ssh
vagrant@stretch:~$ ip a 
...
3: ens6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:0c:d0:3c brd ff:ff:ff:ff:ff:ff
    inet 10.20.30.77/24 brd 10.20.30.255 scope global dynamic ens6
       valid_lft 3565sec preferred_lft 3565sec
    inet6 fe80::5054:ff:fe0c:d03c/64 scope link 
       valid_lft forever preferred_lft forever
```

## Debug output
https://gist.github.com/sourceindex/dde038155a70224ecaae0f2081efcac4

**Comment by sourceindex** [comment] 2018-03-06 09:11
Seem to be an issue of the "debian/stretch64" image, "generic/debian9" also works as expected.

**Comment by electrofelix** [comment] 2018-03-06 09:45
It may also be an issue with vagrant itself, as the code that decides how to write out the network configuration is within the main project rather than plugins.

Vagrant-libvirt really only adjusts the array of network details to separate the management network that is used to perform actions, the rest is passed through verbatim to vagrant to perform the necessary guest actions.

**Comment by viccuad** [comment] 2018-04-02 16:32
I can also reproduce this, using Debian Testing, and the vagrant
libvirt image `debian/stretch64 (libvirt, 9.1.0)`.

In my host, the relevant changes have been:

- [2018-02-08] vagrant 2.0.2+dfsg-2, from [2017-11-02] vagrant 2.0.0+dfsg-1
- [2018-03-04] vagrant-libvirt_0.0.43-2, from [2017-07-27] vagrant-libvirt_0.0.40-1

I have also tried downgrading vagrant-libvirt from 0.0.43 to 0.0.40, it didn't
work.

I cannot reproduce with the same Debian image in another system and:
- Vagrant 1.8.7
- vagrant-libvirt 0.0.40
installed from upstream packages and `vagrant plugin`, though.

**Comment by treytabner** [comment] 2018-05-25 17:05
I think this is because the debian/jessie64/stretch64 images use systemd-network (/etc/systemd/network/*) and not the traditional /etc/network/interfaces file.  See https://lists.debian.org/debian-cloud/2017/07/msg00007.html for more information.

**Comment by gun1x** [comment] 2018-08-27 08:35
I reproduced the bug. Stretch is not getting the static IPs. 

```
 INSERT  gunix  ~  vagrant --version
Vagrant 2.0.2
 INSERT  gunix  ~  libvirtd --version
libvirtd (libvirt) 4.1.0

```

**Comment by viccuad** [comment] 2018-09-01 09:26
I forwarded the bug to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907744.

**Comment by jandd** [comment] 2020-03-03 23:22
The issue is caused by the systemd-networkd script `/etc/systemd/network/99-dhcp.network` that is placed into the Debian images by vmdebootstrap that is used to build these images.

For my use case I added a small shell provisioner that changes this file and restarts systemd-networkd:

```shell
#!/bin/sh

set -e

debootstrap_network=/etc/systemd/network/99-dhcp.network

if grep -q '^Name=\\*' "${debootstrap_network}"; then
  primary_nic=$(ls -1 /sys/class/net | grep -v lo |sort | head -1)
  sed -i "s/^Name=e\\*/Name=${primary_nic})/" \
    "${debootstrap_network}"
  systemctl restart systemd-networkd.service
  echo "Changed systemd network configuration"
else
  echo "Systemd network configuration has already been changed"
fi
```

I add this provisioner to my `Vagrantfile` like this:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "debian/buster64"
  config.vm.network :private_network, :ip => "172.16.3.3"
  ...
  config.vm.provision :shell, path: "change-vmdebootstrap-default-dhcp.sh"
  ...
end
```

This works for my use case but may break in more elaborate setups or when the rudimentary primary NIC detection in my shell script may find the wrong network interface.

**Comment by wdolorito** [comment] 2020-05-14 19:29
I'd been trying to figure this out for a few hours before finding this thread.  I started looking in to the files in /etc/systemd/network/* after seeing @jandd 's solution.  My following version information:

`$ cat /etc/os-release`
```sh
NAME="elementary OS"
VERSION="5.1.4 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.4 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.4"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic
```

`$ vagrant box list`
`debian/buster64 (libvirt, 10.4.0)`

`$ vagrant --version`
`Vagrant 2.0.2`

`$ vagrant plugin list`
`vagrant-libvirt (0.0.43, system)`

My alternate solution is to rename the file `/etc/systemd/network/99-vagrant.network` that is present in the box.

```sh
# fix_libvirt.sh - rename 99-vagrant.network file

#!/bin/sh
mv /etc/systemd/network/99-vagrant.network /etc/systemd/network/100-vagrant.network
systemctl restart systemd-networkd
```
Add the script to the `Vagrantfile` with `config.vm.provision "shell", path: "fix_libvirt.sh"`

**Comment by electrofelix** [comment] 2021-03-22 10:22
Closing this, it looks like recent versions of vagrant have fixed the network configuration for debian guests to behave as expected.
Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.network :private_network, :ip => "172.16.3.3"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
```

Version and bring up:
```
$ vagrant plugin list
vagrant-guests-clearlinux (1.2.4, global)
vagrant-libvirt (0.3.0, global)
vagrant-proxyconf (2.0.10, global)
$ vagrant version
Installed Version: 2.2.13
$ vagrant up --provider libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'debian/buster64' version '10.4.0' is up to date...
==> default: A newer version of the box 'debian/buster64' for provider 'libvirt' is
==> default: available! You currently have version '10.4.0'. The latest is version
==> default: '10.20210228.1'. Run `vagrant box update` to update.
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              test_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Memory:            512M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Nvram:             
==> default:  -- Base box:          debian/buster64
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/test_default.img (20G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Sound Type:	
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Configuring and enabling network interfaces...
```

Then checking for the ip address:
```
$ ping -c 1 172.16.3.3
PING 172.16.3.3 (172.16.3.3) 56(84) bytes of data.
64 bytes from 172.16.3.3: icmp_seq=1 ttl=64 time=0.260 ms

--- 172.16.3.3 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.260/0.260/0.260/0.000 ms
```

Checking VM:
```
$ vagrant ssh -c 'ip addr'
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:ab:fb:a2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.151/24 brd 192.168.121.255 scope global dynamic ens5
       valid_lft 3341sec preferred_lft 3341sec
    inet6 fe80::5054:ff:feab:fba2/64 scope link 
       valid_lft forever preferred_lft forever
3: ens6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:71:6a:23 brd ff:ff:ff:ff:ff:ff
    inet 172.16.3.3/24 brd 172.16.3.255 scope global ens6
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe71:6a23/64 scope link 
       valid_lft forever preferred_lft forever
Connection to 192.168.121.151 closed.
```

**Closed by electrofelix** 2021-03-22 10:22 UTC

**Comment by EmmanuelKasper** [comment] 2021-03-23 07:25
@electrofelix here Debian Maintainer speaking, we changed recently the build tool from vmdeboostrap to fai-diskimage, which is using (rightly) ifupdown instead of systemd-networkd. I guess this this reason assigning a static IP is now working again.

**Comment by alex0z1** [comment] 2022-12-21 04:27
btw, this is still an issue with most recent Fedora https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-37-1.7.x86_64.vagrant-libvirt.box
