### ISSUE TITLE
Error message given during initialization: can't activate json-2.3.0, already activated json-2.5.1

### ISSUE THREAD

**Issue by oz123** [vagrant-libvirt/vagrant-libvirt#1390] opened 2021-10-31 23:13 UTC
### Steps to reproduce
1. Install vagrant  2.2.18
2. vagrant install plugin  vagrant-libvirt
3. vagrant status

### Expected behaviour

Vagrant starts  

### Actual behaviour

```
 $ vagrant status
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: can't activate json-2.3.0, already activated json-2.5.1

```
### System configuration
**OS/Distro version:**:
Gentoo

**Libvirt version:**
app-emulation/libvirt-7.8.0

**Output of `vagrant version; vagrant plugin list`:**
```
$ vagrant version; vagrant plugin list
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: can't activate json-2.3.0, already activated json-2.5.1
vagrant-libvirt (0.6.3, global)

```
**Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`**
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/7449923/vagrant.log)

**Are you using upstream vagrant package or your distros package?**

Distro - 2.2.18-r1

**Comment by electrofelix** [comment] 2021-11-01 12:32
@oz123 while `vagrant plugin expunge --reinstall` can sometimes work, I'd suggest (might be worth backing up `~/.vagrant.d/plugins.json` first) the following instead:
```
vagrant plugin expunge
vagrant plugin install vagrant-libvirt
``` 

And then install any other plugins you need afterwards.

**Comment by oz123** [comment] 2021-11-01 12:36
I tried this a couple of times, forgot to mention. If I install json-2.3.0 globally (and remove 2.5.1) it works.
I also tried to install the json-2.3.0  `~/.vagrant.d`. However, ruby seems to always favor the latest version.
I don't know how to force ruby (vagrant) to accept json-2.3.0 from the local path.

**Comment by electrofelix** [comment] 2021-11-01 12:47
I have 2.5.1 installed on my system and it's working, is there a particular reason you want it to use 2.3.0?

eix tells me I have the following
```
[I] dev-ruby/json
     Available versions:  (2) 2.3.0^t{tbz2} 2.5.1-r1^t{tbz2} ~2.6.1^t
       {doc test RUBY_TARGETS="ruby26 ruby27 ruby30"}
     Installed versions:  2.5.1-r1(2)^t{tbz2}(19:11:58 25/10/21)(-doc -test RUBY_TARGETS="ruby26 ruby27 -ruby30")
     Homepage:            https://github.com/flori/json
     Description:         A JSON implementation as a Ruby extension
```
equery for what is pulling this in gives:
```
dev-lang/ruby-2.6.8 (>=dev-ruby/json-2.0.2[ruby_targets_ruby26])
dev-lang/ruby-2.7.4 (>=dev-ruby/json-2.0.2[ruby_targets_ruby27])
dev-ruby/rubygems-3.1.6 (test ? dev-ruby/json[ruby_targets_ruby26(-)])
                        (test ? dev-ruby/json[ruby_targets_ruby27(-)])
```

**Comment by oz123** [comment] 2021-11-01 12:50
No reason, besides that Vagrant should work :-)
Which vagrant version are you using?

(Side note: I am impressed that you use gentoo! rare case!)

**Comment by electrofelix** [comment] 2021-11-01 12:59
Ah, I'm on 2.2.9, I hadn't upgraded the system vagrant in a while because I'm usually working with rvm in order to be able to switch versions quickly for development. Will kick off an update and check again once it's installed, there might be some quirk with the latest version that is causing an issue.

**Comment by electrofelix** [comment] 2021-11-01 15:09
Updated vagrant to latest distro release:
```
[I] app-emulation/vagrant
     Available versions:  (~)2.2.7-r1^t (~)2.2.9-r1^t{tbz2} (~)2.2.18-r1^t{tbz2} {test +virtualbox RUBY_TARGETS="ruby26 ruby27"}
     Installed versions:  2.2.18-r1^t{tbz2}(14:27:42 01/11/21)(-test RUBY_TARGETS="ruby26 ruby27")
     Homepage:            https://vagrantup.com/
     Description:         A tool for building and distributing development environments

[I] dev-ruby/vagrant_cloud
     Available versions:  (~)2.0.3-r1^t{tbz2} ~3.0.2^t (~)3.0.5^t{tbz2} {doc test RUBY_TARGETS="ruby26 ruby27"}
     Installed versions:  3.0.5^t{tbz2}(14:27:10 01/11/21)(-doc -test RUBY_TARGETS="ruby26 ruby27")
     Homepage:            https://github.com/hashicorp/vagrant_cloud
     Description:         Vagrant Cloud API Library
```

installing the plugin after running `vagrant plugin expunge`
```
$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching builder-3.2.4.gem
Fetching formatador-0.3.0.gem
Fetching fog-core-2.2.4.gem
Fetching multi_json-1.15.0.gem
Fetching fog-json-1.2.0.gem
Fetching nokogiri-1.12.5-x86_64-linux.gem
Fetching fog-xml-0.1.4.gem
Fetching ruby-libvirt-0.7.1.gem
Building native extensions. This could take a while...
Fetching fog-libvirt-0.9.0.gem
Fetching vagrant-libvirt-0.6.3.gem
Installed the plugin 'vagrant-libvirt (0.6.3)'!
```

checking version of dev-ruby/json:
```
[I] dev-ruby/json
     Available versions:  (2) 2.3.0^t{tbz2} 2.5.1-r1^t{tbz2} ~2.6.1^t
       {doc test RUBY_TARGETS="ruby26 ruby27 ruby30"}
     Installed versions:  2.5.1-r1(2)^t{tbz2}(19:11:58 25/10/21)(-doc -test RUBY_TARGETS="ruby26 ruby27 -ruby30")
     Homepage:            https://github.com/flori/json
     Description:         A JSON implementation as a Ruby extension
```

running status command now produces:
```
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: can't activate json-2.3.0, already activated json-2.5.1
```

So definitely reproducible.

**Comment by electrofelix** [comment] 2021-11-01 15:57
can you run `gem info json`, I got the following, so it looks like I had a local gem installed that was causing issues:
```
$ gem info json

*** LOCAL GEMS ***

json (2.5.1, 2.3.1, 2.1.0)
    Author: Florian Frank
    Homepage: http://flori.github.com/json
    License: Ruby
    Installed at (2.5.1): /usr/lib64/ruby/gems/2.6.0
                 (2.3.1): /home/dara/.gem/ruby/2.6.0
                 (2.1.0, default): /usr/lib64/ruby/gems/2.6.0

    JSON Implementation for Ruby
```

Initially I tried running `gem cleanup --user-install` and then `vagrant plugin expunge --reinstall` but that didn't solve the problem.

Then I spotted was that I was still using ruby 2.6.x, so I ran `eselect ruby set 2` to switch to ruby 2.7.x and re-running `gem info json` points out the problem:
```

*** LOCAL GEMS ***

json (2.5.1, 2.3.0)
    Author: Florian Frank
    Homepage: http://flori.github.com/json
    License: Ruby
    Installed at (2.5.1): /usr/lib64/ruby/gems/2.7.0
                 (2.3.0, default): /usr/lib64/ruby/gems/2.7.0

    JSON Implementation for Ruby
```

and can see the issue, the json gem version that is causing all the issues is part of the default gem set.


Looks like this is a bug in vagrant itself in how it's selecting which gems to load when multiple are available. By default with the vagrant provided packages there shouldn't be more than one available, but with a distro installed one, there might be.

Applying the following change solved this for me
```
diff -u /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/bundler.rb.orig /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/bundler.rb
--- /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/bundler.rb.orig	2021-11-01 15:32:04.515282425 +0000
+++ /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/bundler.rb	2021-11-01 15:56:03.443661221 +0000
@@ -258,7 +258,11 @@
       if solution_file&.valid?
         @logger.debug("loading cached solution set")
         solution = solution_file.dependency_list.map do |dep|
-          spec = composed_set.find_all(dep).first
+          spec = composed_set.find_all(dep).select do |dep_spec|
+            next(true) unless Gem.loaded_specs.has_key?(dep_spec.name)
+
+            Gem.loaded_specs[dep_spec.name].version.eql?(dep_spec.version)
+          end.first
           if !spec
             @logger.warn("failed to locate specification for dependency - #{dep}")
             @logger.warn("invalidating solution file - #{solution_file}")
```

Will need gentoo to carry this unless vagrant is happy to accept.

**Comment by oz123** [comment] 2021-11-01 17:52
Yay! Thank you for being so engaged. I thought it was gentoo or some problem with my system. I always feel discomfort when it comes to managing ruby packages in gentoo (because, I can't really program in ruby ...).

**Comment by nochristrequired** [comment] 2022-02-01 19:47
I ran into this problem today on Gentoo w/ Vagrant. Thank you @oz123 for documenting your troubleshooting steps. This is still an issue.

**Comment by tmu-sprd** [comment] 2022-07-08 14:36
For anyone like me, who has this problem on gentoo, do this until fixed upstream:

- create folder `/etc/portage/patches/app-emulation/vagrant`
- create a file in this folder with this name `bundler-gem-select.patch` with this content
```patch
diff --git a/lib/vagrant/bundler.rb b/lib/vagrant/bundler.rb
index eb2caabb0..3feab49b3 100644
--- a/lib/vagrant/bundler.rb
+++ b/lib/vagrant/bundler.rb
@@ -258,7 +258,11 @@ module Vagrant
       if solution_file&.valid?
         @logger.debug("loading cached solution set")
         solution = solution_file.dependency_list.map do |dep|
-          spec = composed_set.find_all(dep).first
+          spec = composed_set.find_all(dep).select do |dep_spec|
+            next(true) unless Gem.loaded_specs.has_key?(dep_spec.name)
+
+            Gem.loaded_specs[dep_spec.name].version.eql?(dep_spec.version)
+          end.first
           if !spec
             @logger.warn("failed to locate specification for dependency - #{dep}")
             @logger.warn("invalidating solution file - #{solution_file}")
```
- re-emerge app-emulation/vagrant

Thanks to @electrofelix for providing the fix.

**Comment by electrofelix** [comment] 2022-08-01 18:17
Fix has been accepted upstream, so should appear in the next release.

**Closed by electrofelix** 2022-08-01 18:17 UTC
