### ISSUE TITLE
Cannot reate 

### ISSUE THREAD

**Issue by Jeremiah-shichengge** [vagrant-libvirt/vagrant-libvirt#1147] opened 2020-09-18 12:29 UTC
### Steps to reproduce
1. fedora 32 server on VMware Workstation 15 Player. 
2. su root, then: # sudo dnf install vagrant libvirt vagrant-libvirt vagrant-sshfs ansible
3. # git clone https://github.com/fedora-infra/the-new-hotness.git
4. # cd the-new-hotness
5. # vagrant up (according to the formal process, this is a cp action: "cp Vagrantfile.example Vagrantfile". But I cannot find the file named Vagrantfile.example, and there is a file named Vagrantfile)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

root@192 the-new-hotness]# vagrant up
Bringing machine 'hotness' up with 'libvirt' provider...
==> hotness: Checking if box 'fedora/32-cloud-base' version '32.20200422.0' is up to date...
==> hotness: Creating image (snapshot of base box volume).
==> hotness: Creating domain with the following settings...
==> hotness:  -- Name:              the-new-hotness_hotness
==> hotness:  -- Domain type:       kvm
==> hotness:  -- Cpus:              4
==> hotness:  -- Feature:           acpi
==> hotness:  -- Feature:           apic
==> hotness:  -- Feature:           pae
==> hotness:  -- Memory:            2048M
==> hotness:  -- Management MAC:    
==> hotness:  -- Loader:            
==> hotness:  -- Nvram:             
==> hotness:  -- Base box:          fedora/32-cloud-base
==> hotness:  -- Storage pool:      default
==> hotness:  -- Image:             /root/.local/share/libvirt/images/the-new-hotness_hotness.img (41G)
==> hotness:  -- Volume Cache:      default
==> hotness:  -- Kernel:            
==> hotness:  -- Initrd:            
==> hotness:  -- Graphics Type:     spice
==> hotness:  -- Graphics Port:     -1
==> hotness:  -- Graphics IP:       127.0.0.1
==> hotness:  -- Graphics Password: Not defined
==> hotness:  -- Video Type:        qxl
==> hotness:  -- Video VRAM:        9216
==> hotness:  -- Sound Type:	
==> hotness:  -- Keymap:            en-us
==> hotness:  -- TPM Path:          
==> hotness:  -- INPUT:             type=mouse, bus=ps2
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: End of file while reading data: Input/output error
[root@192 the-new-hotness]# 

### System configuration
**OS/Distro version:**:
Fedora 32 (Server Edition)
**Libvirt version:**

**Output of `vagrant version; vagrant plugin list`:**

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
Insert debug output inside quotes here (replace ... with whatever command you use to trigger the issue)
```

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro
No.

**Comment by electrofelix** [comment] 2020-11-16 17:50
@Jeremiah-shichengge this sounds like libvirt is not functional on your test system, you'll need to ensure that qemu + libvirt work before vagrant-libvirt can do anything https://github.com/vagrant-libvirt/vagrant-libvirt#installation

You'll also need to ensure that nested virtualization is enabled as otherwise you may see various errors when libvirt API is called asking it to create the VM, though the point at which you got an error suggests something more fundamental is wrong with libvirt itself.

**Comment by electrofelix** [comment] 2020-11-16 17:53
Appears to be a duplicate of #1133 

There is a suggestion in there is to run `virt-host-validate` to establish that libvirt is working as expected, if that passes and it's possible to create VM in libvirt using virt-manager then it's something we'll need to look at here.

**Closed by electrofelix** 2020-11-16 17:53 UTC

**Comment by Jeremiah-shichengge** [comment] 2020-11-16 23:29
Thanks lot.


在 2020年11月17日 01:53，Darragh Bailey<notifications@github.com> 写道：


Appears to be a duplicate of #1133
There is a suggestion in there is to run virt-host-validate to establish that libvirt is working as expected, if that passes and it's possible to create VM in libvirt using virt-manager then it's something we'll need to look at here.
