### ISSUE TITLE
Plugin fails to build on Arch Linux with Vagrant 2.3.0

### ISSUE THREAD

**Issue by sempervictus** [vagrant-libvirt/vagrant-libvirt#1549] opened 2022-08-16 21:59 UTC
**To Reproduce**
1. install vagrant (current/2.3.0) on Arch Linux
2. Try to install this plugin
3. Observe dependency failure

**Expected behavior**
Plugin builds and installs as previously

**Screenshots**
```shell
$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies net-ssh (>= 2.6.5, < 7.0.0) and net-ssh (= 6.2.0.rc2)
  Activated net-ssh-6.2.0.rc2
  which does not match conflicting dependency (>= 2.6.5, < 7.0.0)

  Conflicting dependency chains:
    net-ssh (= 6.2.0.rc2), 6.2.0.rc2 activated

  versus:
    net-scp (= 3.0.0), 3.0.0 activated, depends on
    net-ssh (>= 2.6.5, < 7.0.0)

  Gems matching net-ssh (>= 2.6.5, < 7.0.0):
    net-ssh-6.2.0.rc2
```
**Versions**
```shell
$ pacman -Qi vagrant 
Name            : vagrant
Version         : 2.3.0-2
Description     : Build and distribute virtualized development environments
Architecture    : x86_64
URL             : https://vagrantup.com
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : curl  libarchive  libssh2  libxml2  libxslt  rsync  ruby  xz  perl
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : vagrant-substrate
Replaces        : vagrant-substrate
Installed Size  : 120.77 MiB
Packager        : Jonathan Steel <jsteel@archlinux.org>
Build Date      : Wed 10 Aug 2022 01:49:05 PM EDT
Install Date    : Thu 11 Aug 2022 08:38:01 AM EDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
```shell
$ ruby -v
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
$ which ruby
/usr/bin/ruby
```

**Comment by electrofelix** [comment] 2022-08-16 22:50
Duplicate of #1546, is an upstream big that can't be solved here. Please follow hashicorp/vagrant#12837

**Closed by electrofelix** 2022-08-16 22:50 UTC

**Comment by sempervictus** [comment] 2022-08-16 23:00
Thanks
