### ISSUE TITLE
Ubuntu dependencies do not appear to be available in Cosmic Cuttlefish

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#987] opened 2019-03-29 01:47 UTC
Hello, I am trying to setup vagrant-libvirt on my Ubuntu 18.10 Cosmic Cuttlefish host. However, not all of the Ubuntu packages described in the readme appear to exist, at least in the default Ubuntu repositories. Perhaps the package names have changed? Or is there a particular repository that I should enable?

**Comment by sylvainfaivre** [comment] 2019-04-26 12:42
In Ubuntu 18.10, the `libvirt-bin` package was split into `libvirt-daemon-system` and `libvirt-clients`, so you have to install both these new packages.

Then I got an error when running : 
`vagrant plugin install vagrant-libvirt`

I had to run it with these options : 
`CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt`

Hope this helps.

**Comment by electrofelix** [comment] 2019-10-14 10:51
duplicate of #991

**Closed by electrofelix** 2019-10-14 10:51 UTC
