### ISSUE TITLE
`validate_options': Missing required arguments: libvirt_uri (ArgumentError)

### ISSUE THREAD

**Issue by 14msitaqadeer** [vagrant-libvirt/vagrant-libvirt#568] opened 2016-03-06 06:36 UTC
Hi,
when i use virtualbox as a provider everything is fine but with libvirt i am facing "Missing required arguments: libvirt_uri (ArgumentError)" error, moreover a couple of days ago i was using libvirt it was running perfectly fine. Dont know what happened, i have tried a lot of workarounds but no use.

/home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/service.rb:244:in `validate_options': Missing required arguments: libvirt_uri (ArgumentError)
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/service.rb:268:in `handle_settings'
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/service.rb:98:in `new'
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/services_mixin.rb:16:in `new'
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/compute.rb:65:in `new'
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/services_mixin.rb:4:in `[]'
	from /home/arslan/.vagrant.d/gems/gems/fog-libvirt-0.0.4/lib/fog/libvirt/models/compute/server.rb:269:in `addresses'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/wait_till_up.rb:39:in `block (3 levels) in call'
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/model.rb:72:in `instance_eval'
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/model.rb:72:in `block in wait_for'
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/wait_for.rb:7:in `block in wait_for'
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/wait_for.rb:6:in `loop'
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/wait_for.rb:6:in `wait_for'
	from /home/arslan/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/model.rb:69:in `wait_for'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/wait_till_up.rb:38:in `block (2 levels) in call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/wait_till_up.rb:33:in `block in call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/util/timer.rb:9:in `time'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/wait_till_up.rb:31:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/start_domain.rb:188:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/set_boot_order.rb:60:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_network_interfaces.rb:138:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_networks.rb:79:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/share_folders.rb:20:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_domain.rb:201:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_box_image.rb:109:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_storage_pool.rb:50:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/arslan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

any workaround please??

**Comment by Fodoj** [comment] 2016-03-06 15:53
This happens due to recent `fog-libvirt` gem update. If you use 0.0.3, then everything works fine. With 0.0.4 it breaks with error you've posted.

**Comment by 14msitaqadeer** [comment] 2016-03-06 18:30
yes you are right currently i have installed 0.0.4 veriosn...a week ago it was running fine i did not check the version...probably it was running 0.0.3
how can i degrade to 0.0.3?

**Comment by 14msitaqadeer** [comment] 2016-03-06 18:49
or please suggest any workaround for now, i have a project due :(

**Comment by sford** [comment] 2016-03-07 21:05
Just for future reference, here is the root issue:
https://github.com/fog/fog-libvirt/issues/16

Hopefully a fix will be available soon because the latest version of fog-libvirt has improvements that make `vagrant-libvirt` work better when multiple processes are using libvirt (think CI testing).

To downgrade, you need to first install `0.0.3` and then remove `0.0.4`:

```
gem install -i ~/.vagrant.d/gems --version 0.0.3 fog-libvirt
gem uninstall -i ~/.vagrant.d/gems --version 0.0.4 fog-libvirt
```

**Comment by bkoz** [comment] 2016-03-11 00:23
The gem install downgrade failed on my RHEL7 system (ruby headers missing) but the following worked.
```
$ vagrant plugin install fog-libvirt --plugin-version 0.0.3
```

**Comment by infernix** [comment] 2016-03-28 12:32
I think I'll have to come up with a label that signals the issue is in components we're depending on; `invalid` doesn't quite fit the bill.

Until then I'm labelling this `bug``invalid`since it's not an apparent bug in vagrant-libvirt, it's due to be fixed in `fog` (see  fog/fog-libvirt#16) and we have a workaround available by means of downgrading. Will keep it open until it's resolved to keep it on the radar.

**Comment by infernix** [comment] 2016-06-14 11:44
Upgrading to fog-libvirt > 0.0.4 is waiting for a new ruby-libvirt release which includes http://libvirt.org/git/?p=ruby-libvirt.git;a=commit;h=c2d4192ebf28b8030b753b715a72f0cdf725d313 (see https://github.com/fog/fog-libvirt/commit/21d1b71cc2533fa5892a1a0bba9147ab2e2dca72)

**Comment by voxik** [comment] 2016-09-23 09:32
It seem that new version of ruby-libvirt was released:

https://rubygems.org/gems/ruby-libvirt/versions/0.7.0

And since Chris already updated the Fedora package, it would be nice to get this out to have Vagrant usable.

**Comment by voxik** [comment] 2016-09-26 12:32
Updated fog-libvirt was released as well:

https://rubygems.org/gems/fog-libvirt/versions/0.3.0

**Closed** 2016-10-04 12:14 UTC
Labels: upstream bug

**Comment by axelsimon** [comment] 2021-03-28 21:27
If you arrive here because you get a `/usr/share/gems/gems/fog-core-2.1.2/lib/fog/core/collection.rb:86:in 'new': Initialization parameters must be an attributes hash, got NilClass nil (ArgumentError)` error, **and are using the libvirt provider** (not sure for others) here is something that may help.

In my case, i'd deleted the VM's base image from disk before destroying the VM itself (oops). But while Vagrant would choke on the situation, opening Gnome Boxes let me find the matching VM, shut it down and delete it. From there, i could recreate the VM with Vagrant.

This works because Grome Box is just another front end to libvirt, so it will also display VMs that are in its visible libvirt domains.
You could also use the `virsh` commandline tool to do it too, but i was lazy and used the GUI Gnome Boxes :) (probably something like `virsh destroy my-vm-identifier`

**Comment by electrofelix** [comment] 2021-03-28 22:04
@axelsimon that sounds like another big where we should  handle it on destroy better. Would your mind logging a separate issue
