### ISSUE TITLE
Value for "owner" vagrant option ends up as value for "access" libvirt option

### ISSUE THREAD

**Issue by candeira** [vagrant-libvirt/vagrant-libvirt#1068] opened 2020-01-12 07:55 UTC
```
$ vagrant --version
Vagrant 2.0.2
$ vagrant plugin list
vagrant-libvirt (0.0.43, system)
```

From Vagrantfile:
```
config.vm.define "foo", autostart: false do |foo|
    # lots of it expunged
    foo.vm.synced_folder "../code", "/srv/project", type: "9p",
        disabled: "false", owner: "vagrant", accessmode: "squash"
```

Running `vagrant up`, with the irrelevant lines snipped out:
```
$ vagrant up foo

# snip...

==> python2-libvirt:  /srv/project, opts: {:type=>:"9p", :disabled=>false, :owner=>"vagrant", :accessmode=>"squash", :guestpath=>"/srv/project", :hostpath=>"/home/candeira/foo/code", :__vagrantfile=>true, :target=>"/srv/project", :mount=>true, :readonly=>nil, :mount_tag=>"dbba20a924546d1223f3f7a7f27eaff"}

# snip...

/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/ssh/communicator.rb:257:in `execute': The following SSH command responded with a non-zero exit status. (Vagrant::Errors::LinuxMountFailed)
Vagrant assumes that this means the command failed!

mount -t 9p -o trans=virtio,access=vagrant,version=9p2000.L 'dbba20a924546d1223f3f7a7f27eaff' /srv/project
```

Notice how the mount command passes the string "vagrant" as an access type. The code responsible for this seems to be here:

https://github.com/vagrant-libvirt/vagrant-libvirt/blob/39f9a9d0b455a358917290417bb447396c245034/lib/vagrant-libvirt/cap/mount_p9.rb#L24

**Comment by electrofelix** [comment] 2021-05-27 17:34
Looks like this is a duplicate of #378, going to close this one, assign the original to myself and see if there is something that can be done based on the latest documentation.

**Closed by electrofelix** 2021-05-27 17:34 UTC
