### ISSUE TITLE
undefined method `persistent?' for #<Libvirt::StoragePool:0x007f15f546eeb8>

### ISSUE THREAD

**Issue by maci0** [vagrant-libvirt/vagrant-libvirt#87] opened 2013-11-14 20:58 UTC
maci@nb0815 ~/Desktop/libvirt % vagrant up --provider=libvirt
Bringing machine 'test_vm' up with 'libvirt' provider...
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'test_vm' machine. Please report this as a bug:
```
undefined method `persistent?' for #<Libvirt::StoragePool:0x007f15f546eeb8>

/home/maci/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/requests/compute/list_pools.rb:24:in `pool_to_attributes'
/home/maci/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/requests/compute/list_pools.rb:36:in `find_pool_by_name'
/home/maci/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/requests/compute/list_pools.rb:13:in `block in list_pools'
/home/maci/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/requests/compute/list_pools.rb:12:in `each'
/home/maci/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/requests/compute/list_pools.rb:12:in `list_pools'
/home/maci/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/models/compute/pools.rb:13:in `all'
/home/maci/.vagrant.d/gems/gems/vagrant-libvirt-0.0.11/lib/vagrant-libvirt/action/handle_storage_pool.rb:20:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
/home/maci/.vagrant.d/gems/gems/vagrant-libvirt-0.0.11/lib/vagrant-libvirt/action/set_name_of_domain.rb:26:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:51:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
/home/maci/.vagrant.d/gems/gems/vagrant-libvirt-0.0.11/lib/vagrant-libvirt/action/connect_libvirt.rb:85:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/machine.rb:147:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
```

1 maci@nb0815 ~/Desktop/libvirt % cat Vagrantfile                                                                                  :(
Vagrant.configure("2") do |config|

  # If you are still using old centos box, you have to setup root username for
  # ssh access. Read more in section 'SSH Access To VM'.
  config.ssh.username = "root"

  config.vm.define :test_vm do |test_vm|
    test_vm.vm.box = "lv-centos64"
    test_vm.vm.network :private_network, :ip => '10.20.30.40'
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.storage_pool_name = "default"
  end
end

**Comment by bhundven** [comment] 2015-02-05 23:12
On my centos 7 install I get the same issue, but moving libcurl and the .pc file out of the way before installing the plugin doesn't work. I get the exact same error. Any other info I can provide?

**Comment by bhundven** [comment] 2015-02-05 23:14
Log for previous comment: 
```
$ vagrant up --provider=libvirt
Bringing machine 'test_vm' up with 'libvirt' provider...
/home/bhundven/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/libvirt/requests/compute/list_pools.rb:24:in `pool_to_attributes': undefined method `persistent?' for #<Libvirt::StoragePool:0x00000003691560> (NoMethodError)
        from /home/bhundven/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/libvirt/requests/compute/list_pools.rb:36:in `find_pool_by_name'
        from /home/bhundven/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/libvirt/requests/compute/list_pools.rb:13:in `block in list_pools'
        from /home/bhundven/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/libvirt/requests/compute/list_pools.rb:12:in `each'
        from /home/bhundven/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/libvirt/requests/compute/list_pools.rb:12:in `list_pools'
        from /home/bhundven/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/libvirt/models/compute/pools.rb:11:in `all'
        from /home/bhundven/.vagrant.d/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/handle_storage_pool.rb:20:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /home/bhundven/.vagrant.d/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /home/bhundven/.vagrant.d/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by Pierrotws** [comment] 2015-03-19 14:50
Same problem, also on ArchLinux !

**Comment by doonhammer** [comment] 2015-04-21 16:32
I am having the same problem on Centos 7 with Vagrant 1.7.2 and libvirt 0.0.26. Any pointers to debugging/fixing would be appreciated.

**Comment by pronix** [comment] 2015-04-21 16:33
try to update fog

**Comment by doonhammer** [comment] 2015-04-21 16:53
Pronix - thanks for the suggestion - did a "gem install fog" but did not help.

**Comment by pronix** [comment] 2015-04-21 16:54
try ```vagrant plugin install ...``` or ```vagrant plugin update ...```

**Comment by kampka** [comment] 2015-05-17 19:34
I worked around this issue by installing ruby-libvirt from the AUR and copying it over the version installed in ~/.vagrant.d. It sould keep things working at least for a while.

**Comment by infernix** [comment] 2016-04-08 12:06
I'm flagging this as an upstream bug; if anyone could please report complete steps to replicate the issue under current vagrant (1.8.1+) and vagrant-libvirt (0.0.33) for any host OS, I will attempt to determine whether if we need to file a bug elsewhere.

**Comment by katsel** [comment] 2016-07-04 18:10
I'm currently having that issue under vagrant 1.8.4 and vagrant-libvirt 0.0.33 on Arch Linux. None of the workarounds suggested above did help.

Steps to reproduce:
* `CFLAGS="-DHAVE_VIRDOMAINQEMUMONITORCOMMAND" vagrant plugin install vagrant-libvirt`
(The additional CFLAGS is needed because a plain `vagrant plugin install` fails on Arch. An alternative is the install command mentioned [in the Arch wiki](https://wiki.archlinux.org/index.php/Vagrant#vagrant-libvirt) which also worked to install the plugin).
* `vagrant init iknite/trusty64`
* `vagrant up --provider libvirt`

It fails with an error
```
Bringing machine 'default' up with 'libvirt' provider...
/home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_pools.rb:24:in `pool_to_attributes': undefined method `persistent?' for #<Libvirt::StoragePool:0x00032ca46c70e0> (NoMethodError)
	from /home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_pools.rb:36:in `find_pool_by_name'
	from /home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_pools.rb:13:in `block in list_pools'
	from /home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_pools.rb:12:in `each'
	from /home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_pools.rb:12:in `list_pools'
	from /home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/models/compute/pools.rb:11:in `all'
	from /home/me/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/handle_storage_pool.rb:26:in `block in call'
	from /home/me/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/handle_storage_pool.rb:23:in `synchronize'
	from /home/me/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/handle_storage_pool.rb:23:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/me/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:225:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:200:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/environment.rb:561:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:186:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:186:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by electrofelix** [comment] 2016-07-05 13:24
@katsel Using the CFLAGS option results in a broken native executable, instead better to switch the ld executable used for the duration of the plugin installation.

See https://github.com/vagrant-libvirt/vagrant-libvirt/issues/346#issuecomment-102145567

You'll need to completely uninstall vagrant-libvirt, then ensure that the ruby-libvirt plugin is completely removed. Switch the ld executable to the gold version, install vagrant-libvirt and then switch it back, and you should find that it is now able to correctly talk to libvirt through the ruby bindings.

**Comment by katsel** [comment] 2016-07-06 13:29
@electrofelix Thanks for that hint!

I carefully followed the steps mentioned, and plugin install works without any issues, which is awesome. However, I'm still getting the same error when trying to bring the box up.

I also tried the CentOS box mentioned in the README of this project, same error.

Is there something else I am missing?

```
# remove old plugin
$ vagrant plugin uninstall vagrant-libvirt
Uninstalling the 'vagrant-libvirt' plugin...

# check that ruby-libvirt is removed
$ ls ~/.vagrant.d/gems/gems/
domain_name-0.5.20160615  ffi-1.9.12  vagrant-lxc-1.2.1

# use ld.gold
$ sudo ln -fs /usr/bin/ld.gold /usr/bin/ld

# re-install vagrant-libvirt
$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Installed the plugin 'vagrant-libvirt (0.0.33)'!

# attempt to start container
$ vagrant up --provider libvirt
Bringing machine 'default' up with 'libvirt' provider...
/home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_pools.rb:24:in `pool_to_attributes': undefined method `persistent?' for #<Libvirt::StoragePool:0x000329946c4bf0> (NoMethodError)
	from /home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_pools.rb:36:in `find_pool_by_name'
	from /home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_pools.rb:13:in `block in list_pools'
	from /home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_pools.rb:12:in `each'
	from /home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_pools.rb:12:in `list_pools'
	from /home/me/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/models/compute/pools.rb:11:in `all'
	from /home/me/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/handle_storage_pool.rb:26:in `block in call'
	from /home/me/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/handle_storage_pool.rb:23:in `synchronize'
	from /home/me/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/handle_storage_pool.rb:23:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/me/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:225:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:200:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/environment.rb:561:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:186:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:186:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by katsel** [comment] 2016-07-20 18:46
ping @infernix - I reported the steps to reproduce the issue above. Please let me know if there's anything else I can do.

**Comment by infernix** [comment] 2016-07-20 19:07
@katsel i have installation testing for all distros except Arch I'm afraid. It's still on my list of distros to add.

As for the issue, I really am none the wiser after reviewing this, but it surely is an issue with how ruby-libvirt is being invoked/compiled. fog-libvirt just calls against ruby-libvirt and that interacts with libvirt itself.

If you look at ruby-libvirt, you can find:

```c

#if HAVE_VIRSTORAGEPOOLISPERSISTENT
/*
 * call-seq:
 *   pool.persistent? -> [true|false]
 *
 * Call virStoragePoolIsPersistent[http://www.libvirt.org/html/libvirt-libvirt.html#virStoragePoolIsPersistent]
 * to determine if this storage pool is persistent.
 */
static VALUE libvirt_storage_pool_persistent_p(VALUE p)
{
    ruby_libvirt_generate_call_truefalse(virStoragePoolIsPersistent,
                                         ruby_libvirt_connect_get(p),
                                         pool_get(p));
}
#endif
```

Maybe you need to compile with that flag or otherwise determine why that flag isn't active during compilation? Is it in your extconf.h for the ruby-libvirt-built `_libvirt.so`?

**Comment by katsel** [comment] 2016-08-05 11:33
@infernix: We found that one more step is required to reproduce the issue on Arch - it only happens when the ruby package has been installed via system package manager.

Meanwhile we got that problem fixed on my system. We did that by completely uninstalling all vagrant plugins, deleting the folder, emptying the gem cache, removing system ruby and re-installing the plugin according to the [Arch wiki](https://wiki.archlinux.org/index.php/Vagrant#vagrant-libvirt):

```
$ CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib \
with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' \
GEM_HOME=~/.vagrant.d/gems \
GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems \
PATH=/opt/vagrant/embedded/bin:$PATH \
  vagrant plugin install vagrant-libvirt
```

It seems like the issue stems from the fact that system ruby and vagrant's own ruby get mixed up in weird ways during plugin install.

**Comment by infernix** [comment] 2016-10-12 15:11
I'm going to close this one for now since we've added the compilation option to the documentation and I'm about to add some CI to test for these types of issues across all popular distros.

If this pops up again feel free to comment/reopen!

**Closed by infernix** 2016-10-12 15:11 UTC
Labels: needinfo, upstream bug
