### ISSUE TITLE
vagrant up fails to start some guests, --no-parallel succeeds

### ISSUE THREAD

**Issue by josefbacik** [vagrant-libvirt/vagrant-libvirt#1495] opened 2022-05-17 17:26 UTC
**Describe the bug**
Using kdevops (https://github.com/linux-kdevops/kdevops) with vagrant+vagrant-libvirt, the bringup phase, which actually starts the vm's, will fail to start some of the guests.  If I switch to --no-parallel it works fine.

**To Reproduce**
1. Checkout kdevops
2. make menuconfig and select the btrfs/fstests workflow
3. make
4. make bringup

**Expected behavior**
It should start all of the vms, instead it only starts a few.

**Screenshots**
I get the following error for some number of the VMS
```
An unexpected error occurred when executing the action on the
'kdevops-btrfs-simple-zns-dev' machine. Please report this as a bug:

constant VagrantPlugins::ProviderLibvirt::Action::WaitForCommunicator not defined

                b2.use WaitForCommunicator, [:running]
                       ^^^^^^^^^^^^^^^^^^^

/usr/share/vagrant/gems/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action.rb:55:in `block (2 levels) in action_up'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:47:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_check_outdated.rb:93:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

**Versions (please complete the following information):**:
- Libvirt version: libvirt-8.1.0-2.fc36.x86_64
- Vagrant version [output of `vagrant version`]: Installed Version: 2.2.19
- Vagrant flavour [Upstream or Distro]: Fedora 36 packages
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: vagrant-libvirt (0.7.0, system)

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
```
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/8710381/vagrant.log)
```

**A Vagrantfile to reproduce the issue:**
https://github.com/linux-kdevops/kdevops/blob/master/vagrant/Vagrantfile

**Comment by electrofelix** [comment] 2022-05-17 17:56
This is a duplicate of #1445, if you upgrade to 0.8.2, you should no longer experience this

**Closed by electrofelix** 2022-05-17 17:56 UTC
