### ISSUE TITLE
Unable to change machine type from default

### ISSUE THREAD

**Issue by alff** [vagrant-libvirt/vagrant-libvirt#472] opened 2015-10-01 18:01 UTC
Hi.

Before this moment i've used default machine type for all of my VMs. But recently i've tried to change on something else and it wasn't successful.

So what do i have:
- CentOS Linux release 7.0.1406
- 3.10.0-123.20.1.el7.x86_64
- qemu-kvm-1.5.3-86.el7_1.1.x86_64
- libvirt-1.2.8-16.el7_1.4.x86_64
- vagrant-1.7.2-1.x86_64
- vagrant-libvirt (0.0.31)

Example of my VM configuration:
```
   config.vm.define "alex-mn03" do |node|
       node.vm.box = "centos711"
       node.vm.hostname = "alex-mn03"
       node.ssh.username = "vagrant"
       node.ssh.password = "vagrant"
       node.vm.synced_folder ".", "/vagrant", disabled: true
       node.vm.provider :libvirt do |libvirt|
           libvirt.memory = 2048
           libvirt.nested = true
           libvirt.cpus = 2
           libvirt.driver = "kvm"
           libvirt.connect_via_ssh = false
           libvirt.username = "root"
           libvirt.disk_bus = "sata"
           #libvirt.machine_type = "pc-q35-1.6"
           libvirt.storage_pool_name = "default"
       end
       node.vm.network :public_network, :dev => "br0", :mode => "bridge", :type => "bridge", ip: "10.44.3.192", :netmask => "255.255.240.0"
       node.vm.network :private_network, :libvirt__network_name => "private", ip: "192.168.50.192"
   end
```
So if i try to comment out 'libvirt.machine_type' it throws exception:
```
"There was an error talking to Libvirt. The error message is shown
below:

Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: qemu-kvm: -machine pc-q35-1.6,accel=kvm,usb=off: Unsupported machine type
Use -machine help to list supported machines!"
```
```
$ qemu-system-x86_64 -machine help
Supported machines are:
pc-0.13              Standard PC (i440FX + PIIX, 1996)
pc                   Standard PC (i440FX + PIIX, 1996) (alias of pc-i440fx-2.0)
pc-i440fx-2.0        Standard PC (i440FX + PIIX, 1996) (default)
pc-1.0               Standard PC (i440FX + PIIX, 1996)
pc-q35-1.7           Standard PC (Q35 + ICH9, 2009)
pc-1.1               Standard PC (i440FX + PIIX, 1996)
q35                  Standard PC (Q35 + ICH9, 2009) (alias of pc-q35-2.0)
pc-q35-2.0           Standard PC (Q35 + ICH9, 2009)
pc-i440fx-1.4        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.5        Standard PC (i440FX + PIIX, 1996)
pc-0.14              Standard PC (i440FX + PIIX, 1996)
pc-0.15              Standard PC (i440FX + PIIX, 1996)
pc-q35-1.4           Standard PC (Q35 + ICH9, 2009)
isapc                ISA-only PC
pc-0.10              Standard PC (i440FX + PIIX, 1996)
pc-1.2               Standard PC (i440FX + PIIX, 1996)
pc-0.11              Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.7        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.6        Standard PC (i440FX + PIIX, 1996)
none                 empty machine
pc-q35-1.5           Standard PC (Q35 + ICH9, 2009)
pc-q35-1.6           Standard PC (Q35 + ICH9, 2009)
pc-0.12              Standard PC (i440FX + PIIX, 1996)
pc-1.3               Standard PC (i440FX + PIIX, 1996)
```
Any thoughts?

**Comment by infernix** [comment] 2016-10-07 17:50
Please retest this with a more recent version of **upstream vagrant** and vagrant-libvirt, and use the current master of vagrant-libvirt if possible.

To test against current master, you can create an installable gem:
1. Do a `git clone https://github.com/vagrant-libvirt/vagrant-libvirt.git`
2. Run `gem build vagrant-libvirt.gemspec` inside the cloned dir, which generates a `.gem` file
3. Optionally uninstall the existing plugin with `vagrant plugin uninstall vagrant-libvirt`
3. Install the latest master gem with `vagrant plugin install /path/to/gem`

If the problem can be reproduced, please report back as verbose as possible. Thanks!

**Comment by infernix** [comment] 2016-10-07 17:56
FWIW there were a number of changes related to this; I've just tested and it works fine here, so if it doesn't work for you please post full debug logs.

**Comment by infernix** [comment] 2016-10-12 15:07
Closing this due to no further updates/info. Please free to update or reopen this ticket if required. Thanks!

**Closed by infernix** 2016-10-12 15:07 UTC
Labels: question
