### ISSUE TITLE
qemu-img: could not open old backing file ''

### ISSUE THREAD

**Issue by nvtkaszpir** [vagrant-libvirt/vagrant-libvirt#483] opened 2015-10-11 20:32 UTC
When running vagrant package it seems like qemu-img is doing rebase but with empty backing file. Moreover it looks like ``backing`` variable is not used at all, thus it causes error.

https://github.com/pradels/vagrant-libvirt/blame/master/lib/vagrant-libvirt/action/package_domain.rb#L37

while ``backing`` variable is checked in line 29 in the same file.

**Comment by infernix** [comment] 2016-10-07 16:57
This is referring to old code which has since been replaced with virt-sysprep; I'm therefore closing this.

**Closed by infernix** 2016-10-07 16:57 UTC

**Comment by nvtkaszpir** [comment] 2016-10-07 17:07
Please elaborate where the code was replaced with virt-sysprep?
From what I see the issue still can occur because qemu-img command is still present.

**Comment by infernix** [comment] 2016-10-07 17:47
Actually, upon closer inspection this behaviour seems entirely correct.

Yes, it does invoke qemu-img, and as far as I can tell intentionally with *no* new backing image specified. What it seems to be doing is the equivalent of `qemu-img convert -p box-with-backingfile.img -O qcow2  box-without-backingfile.img` but it does it in-place.

So I don't see any bug or issue here. If you can reproduce a problem, please show me how.
