### ISSUE TITLE
Failing to start without a vm.box.

### ISSUE THREAD

**Issue by loood** [vagrant-libvirt/vagrant-libvirt#1534] opened 2022-08-06 01:51 UTC
**Describe the bug**
If I don't specify a vm.box (eg `vm.box = "pace/empty"`) I get the following error below But with vm.box I have no problem.

```
$ vagrant up asd
Bringing machine 'asd' up with 'libvirt' provider...
Traceback (most recent call last):
        30: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        29: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
        28: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
        27: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
        26: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
        25: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
        24: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
        23: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
        22: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
        21: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
        20: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        19: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        18: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        17: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
        16: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        15: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
        14: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
        13: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
        12: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
        11: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
        10: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
         9: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         8: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
         7: from /home/loood/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'
         6: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
         5: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/provision.rb:80:in `call'
         4: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
         3: from /home/loood/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
         2: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
         1: from /home/loood/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:101:in `call'
/home/loood/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:101:in `lookup_domain_by_uuid': no implicit conversion of nil into String (TypeError)
$
```

This is the Vagrantfile
```
Vagrant.configure(2) do |config|

  config.vm.define "asd" do |machine_config|
    #machine_config.vm.box = "pace/empty"
    machine_config.vm.provider :libvirt do |pxe|
      pxe.memory = 7000
      pxe.cpus = 2
      pxe.boot 'network'

    end
  end
end
```

**To Reproduce**
1. With the Vagrantfile above run `vagrant up asd`
2. The error comes up

**Expected behavior**
I expect the vm to start.

**Versions (please complete the following information):**:
- Libvirt version:
```
$ dpkg -l libvirt-daemon
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version           Architecture Description
+++-==============-=================-============-=================================
ii  libvirt-daemon 6.0.0-0ubuntu8.16 amd64        Virtualization daemon
```
- Vagrant version [output of `vagrant version`]:
```
$ vagrant version
Installed Version: 2.2.19
Latest Version: 2.2.19

You're running an up-to-date version of Vagrant!
```
- Vagrant flavour [Upstream or Distro]: Upstream via hasicorp's apt repo
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
```
$ vagrant plugin list
vagrant-libvirt (0.9.0, global)
```
**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
```
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/9274222/vagrant.log)

```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure(2) do |config|

  config.vm.define "asd" do |machine_config|
    machine_config.vm.provider :libvirt do |pxe|
      pxe.memory = 7000
      pxe.cpus = 2
      pxe.boot 'network'

    end
  end
end
```

**Comment by loood** [comment] 2022-08-06 02:37
This may be a dup or related to these. As the link link did, installing version 0.7.0 works.
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1519
https://github.com/hashicorp/vagrant/issues/12792
https://github.com/cfm/terraform-metal-securedrop-staging/pull/11

**Comment by electrofelix** [comment] 2022-08-06 10:29
It's a duplicate of #1508, which although fixed, hasn't been released yet as I'm still working on some fixes for the new docs generation

**Comment by electrofelix** [comment] 2022-08-16 17:00
Plan to do a release shortly which will make the fix for this available.

**Closed by electrofelix** 2022-08-16 17:00 UTC
