### ISSUE TITLE
Could not bridge multiple public networks

### ISSUE THREAD

**Issue by uilianries** [vagrant-libvirt/vagrant-libvirt#475] opened 2015-10-05 18:17 UTC
This is my current scenario:

![testbed1](https://cloud.githubusercontent.com/assets/4870173/10289070/ecd65c52-6b72-11e5-81f8-5dc6caff8a43.jpg)

I would like create 7 bridges, send packages from eth1 in VM and receive at eth2 in VM.
However, when I send some package from eth1, the data flows until p5p2 and dont arrive at eth2.
The the same scenario works when I use virtualbox as provider. So, what is the problem here?

My current Vagrantfile is:

```
VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # SSH
  config.ssh.forward_agent = true
  config.ssh.insert_key = false

  # Agent 01 Configuration
  config.vm.define :agent01, primary: true do |agent01|

    # Box
    agent01.vm.box = 'trusty32'
    agent01.vm.hostname = 'agent01'
    agent01.vm.synced_folder './', '/vagrant', type: 'rsync'

    # Network
    agent01.vm.network :public_network,
      :ip => "101.101.101.13",
      :dev => 'p5p1', 
      :mode => 'bridge'

    agent01.vm.network :public_network,
      :ip => "103.103.103.15",
      :dev => "p5p2", 
      :mode => 'bridge'

    agent01.vm.network :public_network,
      :ip => "102.102.102.14",
      :dev => "p5p3",
      :mode => 'bridge'

    agent01.vm.network :public_network,
      :ip => "104.104.104.16",
      :dev => "p5p4",
      :mode => 'bridge'

    agent01.vm.network :public_network,
      :ip => '100.100.100.12',
      :dev => 'eth0',
      :mode => 'bridge'

    agent01.vm.network :public_network,
      :ip => "105.105.105.17",
      :dev => "eth1", 
      :mode => 'bridge'

    agent01.vm.network :public_network,
      :ip => "106.106.106.18", 
      :dev => "eth2",
      :mode => 'bridge'

    # Provider VIRT
    agent01.vm.provider  :libvirt do |machine|
      machine.memory = 1024
      machine.driver = "kvm"
      machine.cpus = 1
    end #domain

  end # agent01
end # config

```

**Comment by electrofelix** [comment] 2016-02-26 14:15
Considering you've numbered the IP's in what looks to be a particular sequence across p5p1 to p5p4, but inverted the values assigned to p5p2 and p5p3, can you confirm that you're communicating with the correct devices?

Alternatively I've encountered some networking issues within vagrant-libvirt around device ordering and assignment of addresses, but these do appear to be dependent on whether the guest kernel reorders the devices.

I've traced my problem as far as that vagrant-libvirt is assuming a particular device ordering on the guest machine, but as some kernels can see the devices appearing in an order different to how they were defined in the libvirt XML this can apply the given IP to a device attached to a different virtual network thus preventing communication.

Since it's random though, I would have expected it should only cause the above issue some of the time. so would be useful if you could confirm that a similar issue was occurring or if it's due to using the wrong IP accidentally.

**Comment by infernix** [comment] 2016-10-07 17:10
This is a bit hard to reproduce since I don't have that many nics. Could you elaborate on the issue? Have you ran wireshark against the various interfaces to see where traffic is (or isn't) going?

**Comment by infernix** [comment] 2017-08-03 17:25
Closing this due to no further updates/info. Please free to update or reopen this ticket if required. Thanks!

**Closed by infernix** 2017-08-03 17:25 UTC
Labels: needinfo, question
