### ISSUE TITLE
Reproducible can't resolve host

### ISSUE THREAD

**Issue by littlesandra88** [vagrant-libvirt/vagrant-libvirt#1056] opened 2019-10-25 14:19 UTC
### Steps to reproduce
1. `curl https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64` approx 15 times

### Expected behaviour
It should download the content

### Actual behaviour
Approx every 15 time it gives `curl: (6) Could not resolve host: github.com; Unknown error`

### System configuration
Fedora 30

**Libvirt version:**
libvirt-5.1.0-9.fc30.x86_64

**Output of `vagrant version; vagrant plugin list`:**
```
Installed Version: 2.2.5

Vagrant was unable to check for the latest version of Vagrant.
Please check manually at https://www.vagrantup.com
vagrant-libvirt (0.0.45, system)
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
The problem is inside the machine.
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure('2') do |config|

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.host = 'localhost'
    libvirt.uri = 'qemu:///system'
    libvirt.management_network_device = 'virbr0'
    libvirt.storage_pool_name = "default"
  end

  config.ssh.insert_key = false
  config.ssh.private_key_path  = "config/ssh/insecure_private_key"

  config.vm.box = 'centos/7'

  config.vm.define "master" do |m|
     m.vm.hostname = "master"
     m.vm.provider :libvirt do |libvirt|
       libvirt.memory = 2048
       libvirt.cpus = 2
     end
     m.vm.network :private_network, :ip => '192.168.122.230', :libvirt__forward_mode => 'none', :libvirt__network_name => 'default'
  end

end
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by electrofelix** [comment] 2019-10-25 15:18
There is nothing we can do to fix issues with a guest VM having DNS resolving issues.

This typically means there is an issue with the libvirt dnsmasq on your host machine, and or an issue on your guest machine with resolvconf. Neither of which can be impacted with vagrant-libvirt.

You likely will need to talk to the CentOS community to debug why the VM is having issues resolving hosts. I would check to make sure that the private network you've added isn't getting used as the default route at any point, just as you've set the forward mode to none to disable routing, if it is, it's an issue with the CentOS guest, but seems unlikely.

You may discover that your host/guest requires a different network nic model to be presented for a stable network, so experimenting with different values for `:nic_mode` may help, but you'll have to check the documentation for your libvirt version for which types are possible. See https://libvirt.org/formatdomain.html#elementsNICSModel

**Closed by electrofelix** 2019-10-25 15:18 UTC

**Comment by littlesandra88** [comment] 2019-10-28 13:43
Thanks for the detailed reply!

It turns out to be a known bug for the currently latest CentOS. https://blog.centos.org/2019/07/updated-centos-vagrant-images-available-v1905-01/

There is a workaround for VirtualBox, but sadly not for libvirt.

**Comment by electrofelix** [comment] 2019-10-29 10:55
So part of the problem with such a workaround is that vagrant-libvirt needs the network to be able to manage the VM from the host. So just disabling NAT is likely to prevent management, resulting in the VM coming up.

It's a shame there isn't more detail on what the underlying issue is likely to be, because it suggests there is a problem performing resolvconf lookups that result in talking to the host.

One workaround you could look at is hardcoding the resolv.conf in the guest after it comes up to an external DNS resolver such as google, and see if that results in a similar workaround.

When doing testing, I would disable the private network you have added as it'll just confuse things given there is also a management network that requires NAT in order to allow connections from the host into the VM over the network to work.

If hardcoding the DNS hosts to use for resolving doesn't help, you can subsequently with the private network set to route and forcing the routing table in the guest to use the private network as the default device for outbound requests. That should skip using the management network device for DNS lookups going outside, but again you might still need to hard code the DNS server addresses to use for lookups.

This all sounds like a network stack issue for UDP connections within the guest, so depending on whether the problem is located, you may discover that you get some joy in changing the network device emulation if it turns out the problem is buried in the kernel rather than userspace. Its a long shot as much of the stack would be the same, but any bugs in something like virtio drivers in the userspace would only show up in VMs and not real installations. That may mean that switching to an e1000 device or one of the others might avoid some subtle bug between kernel driver -> kernel network for UDP as virtio is in trying to reduce the amount of data being copied around to emulate the network, which means it's more likely for the mistakes in specific scenarios to result in missing packets that are taken care of by TCP but just result in lack of response for UDP.

This is all highly speculative, but given that switching the guess to use different network drivers is as simple as setting `nic_model_type` via the configuration to and doing a destroy/up, see https://libvirt.org/formatdomain.html#elementsNICSModel for the list of values available. I'd generally just stick with trying one of `rtl8139 e1000 virtio`, and as `virtio` may be causing issues, should be straight forward to test the other two.
