### ISSUE TITLE
CentOS images do not work without NetworkManager

### ISSUE THREAD

**Issue by greg-hellings** [vagrant-libvirt/vagrant-libvirt#458] opened 2015-09-15 15:53 UTC
Vagrantfile:
```
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.1.101", netmask: "255.255.255.0"
end
```

Commands:
$ vagrant up
$ vagrant ssh
$ # sudo yum remove -y NetworkManager
$ # exit
$ vagrant halt
$ vagrant up

This part hangs here:
```
[greg@localhost bugs]$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
```
After I kill this up and issue another ``vagrant up`` immediately afterwards, the box is re-provisioned from the base and continues working.

I haven't tested if this is specific to the centos/7 image, but that's the image I'm most interested in. I'm using the current versions of the software from the Fedora 22 repositories.
```
[greg@localhost bugs]$ dnf info vagrant-libvirt
Last metadata expiration check performed 21 days, 21:27:01 ago on Mon Aug 24 13:05:49 2015.
Installed Packages
Name        : vagrant-libvirt
Arch        : noarch
Epoch       : 0
Version     : 0.0.26
Release     : 3.fc22
Size        : 153 k
Repo        : @System
Summary     : libvirt provider for Vagrant
URL         : https://github.com/pradels/vagrant-libvirt
License     : MIT
Description : libvirt provider for Vagrant.

[greg@localhost bugs]$ dnf info libvirt
Last metadata expiration check performed 21 days, 21:27:06 ago on Mon Aug 24 13:05:49 2015.
Installed Packages
Name        : libvirt
Arch        : x86_64
Epoch       : 0
Version     : 1.2.13.1
Release     : 2.fc22
Size        : 0.0  
Repo        : @System
Summary     : Library providing a simple virtualization API
URL         : http://libvirt.org/
License     : LGPLv2+
Description : Libvirt is a C toolkit to interact with the virtualization capabilities
            : of recent versions of Linux (and other OSes). The main package includes
            : the libvirtd server exporting the virtualization support.

[greg@localhost bugs]$ dnf info vagrant
Last metadata expiration check performed 21 days, 21:27:24 ago on Mon Aug 24 13:05:49 2015.
Installed Packages
Name        : vagrant
Arch        : noarch
Epoch       : 0
Version     : 1.7.2
Release     : 10.fc22
Size        : 1.4 M
Repo        : @System
From repo   : updates
Summary     : Build and distribute virtualized development environments
URL         : http://vagrantup.com
License     : MIT
Description : Vagrant is a tool for building and distributing virtualized development
            : environments.
```

When I attach to the running host with virt-manager, ``ip a`` displays the 192.168.1.101 IP address attached to eth1 as I would expect. However, all network commands fail with "connect: Network is unreachable".

**Comment by greg-hellings** [comment] 2015-09-21 14:15
Any help on this?

**Comment by pronix** [comment] 2015-09-21 14:17
only psychological support :)

**Comment by alvaroaleman** [comment] 2015-11-30 13:57
Not exactly sure what the root cause for this is, but it can be fixed by appending ``DEVICE=eth0`` to ``/etc/sysconfig/network-scripts/ifcfg-eth0``:

```bash
sudo su
echo DEVICE=eth0 >> /etc/sysconfig/network-scripts/ifcfg-eth0
```

**Comment by infernix** [comment] 2016-10-07 18:00
Unfortunately this is entirely up to the guest OS; vagrant-libvirt doesn't have any capabilities to sort out issues pertaining to failure in guest OS networking bring-up. 

And even if you feel that this needs to be addressed, it would have to be done in the OS specific Vagrant (_not vagrant-libvirt_) network config scripts (or you can take it up with whoever uploads the images to atlas.hashicorp.com)

So I'm closing this as there isn't anything to do here. If the user decides to alter the guest OS network config, it is up to the user to ensure it works correctly.

**Closed by infernix** 2016-10-07 18:00 UTC
