### ISSUE TITLE
nested virtualization: Vagrant VM gets frozen while installing another VM with packer

### ISSUE THREAD

**Issue by Wenzel** [vagrant-libvirt/vagrant-libvirt#847] opened 2018-01-05 11:39 UTC
### Steps to reproduce
1. run `vagrant up` with the Vagrantfile provided
2. wait for the Vagrant VM to become unresponsive (frozen)

### Expected behaviour
The ansible playbook should have been executed without any issue

### Actual behaviour
The Vagrant VM is frozen at some point during the installation of Windows by packer

### System configuration
**OS/Distro version:**: Ubuntu 16.04.3

**Libvirt version:** 1.3.1

**Output of `vagrant version; vagrant plugin list`:**
~~~
vagrant-libvirt (0.0.40)
vagrant-share (1.1.9, system)
  - Version Constraint: > 0
~~~

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
Not relevant.

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure(2) do |config|
    config.vm.box = "debian/jessie64"

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 1
        libvirt.memory = 4000
        libvirt.nic_model_type = "virtio"
        libvirt.driver = "kvm"
        libvirt.nested = true
    end

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = '2.0'
        ansible.verbose =  '-vvv'
        ansible.playbook = "playbook.yml"
    end
end
```

And the Ansible playbook:
~~~
---
- hosts: default
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - libvirt-daemon-system
        - unzip

    - name: add user to libvirt group
      user:
        name: vagrant
        groups: libvirt
        append: yes

    - name: enable default network as autostart
      command: virsh -c qemu:///system net-autostart default

    - name: download packer
      get_url:
        url: https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
        dest: /root/packer.zip

    - name: unzip packer
      unarchive:
        src: /root/packer.zip
        dest: /root
        remote_src: yes

    - name: download windows packer template
      get_url:
        url: https://raw.githubusercontent.com/KVM-VMI/nitro/master/tests/vm_templates/windows.json
        dest: /root/windows.json

    - name: download windows var file
      get_url:
        url: https://raw.githubusercontent.com/KVM-VMI/nitro/master/tests/vm_templates/windows_7_x64.json
        dest: /root/windows_7_x64.json

    - name: create answer_file tree
      file:
        path: /root/answer_files/7
        state: directory

    - name: download Autounattended.xml
      get_url:
        url: https://raw.githubusercontent.com/KVM-VMI/nitro/master/tests/vm_templates/answer_files/7/Autounattend.xml
        dest: /root/answer_files/7/Autounattend.xml

    - name: build vm
      command: ./packer build --var-file=windows_7_x64.json windows.json
      args:
        chdir: "/root"
~~~

**Are you using upstream vagrant package or your distros package?**
Upstream

Thanks a lot.

**Comment by infernix** [comment] 2018-01-05 11:42
You're going to have to look with virt-manager what the state of the VM is. This does not look like a vagrant-libvirt issue to me if a VM freezes.

**Comment by Wenzel** [comment] 2018-01-05 11:45
@infernix thanks for your reply.
Do you know how i could get some support on this issue ?
Where should i look ?
What do you mean by looking at virt-manager to get the state of the VM ?

All i know is that even the tty is frozen in virt-viewer.
I would like to debug a bit further to understand what is happening.

Thank you.

**Comment by electrofelix** [comment] 2018-01-10 21:18
It means that if the vm locks up to the point that even the tty in virt-viewer is not responsive, then it's an issue between libvirt, the kernel, and your VM image. You'll need to debug why the VM hung up, there isn't anything that vagrant-libvirt would have been doing at that point or could do in the future to fix.

**Comment by electrofelix** [comment] 2018-01-10 21:20
BTW assigning a single CPU to a VM that you plan to run a nested vm on is unlikely to perform well, maybe try with 2 or 3 vcpu's assigned to it.

**Comment by electrofelix** [comment] 2021-05-14 12:54
Tried to reproduce and looks like the machine disk gets filled up:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1       9.2G  9.1G     0 100% /
udev             10M     0   10M   0% /dev
tmpfs           774M  8.4M  766M   2% /run
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
tmpfs           387M     0  387M   0% /run/user/1000
```

Suggest to use additional storage which can be configured.

**Closed by electrofelix** 2021-05-14 12:54 UTC
Labels: needinfo
