### ISSUE TITLE
UDP port forwarding not working, always falls back to TCP

### ISSUE THREAD

**Issue by kivoli** [vagrant-libvirt/vagrant-libvirt#812] opened 2017-09-12 13:43 UTC
Note: First created for [Vagrant](https://github.com/mitchellh/vagrant/issues/8965) itself but seems to be a provider issue.

### Steps to reproduce
1. Create new Vagrant environment
```sh
cd $(mktemp -d) && cat >Vagrantfile <<EOF
# -*- mode: ruby -*-
# vi: set ft=ruby :
# vim: ft=ruby:sw=2:ts=2:ss=2:expandtab

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "debian/stretch64"
  config.vm.network 'forwarded_port', host: 6666, guest: 6666, protocol: 'udp'
end
EOF
```
2. Run `vagrant up`
3. Check port forwardings `netstat -lnp | grep 6666`

### Expected behavior
Port 6666 should be forwarded for protocol UDP.

### Actual behavior
Port 666 is forwarded for protocol TCP.
```sh
% netstat -lnp | grep 666
tcp        0      0 127.0.0.1:6666          0.0.0.0:*               LISTEN      12186/ssh           
tcp6       0      0 ::1:6666                :::*                    LISTEN      12186/ssh  
```

### Vagrant version
```sh
~ % vagrant -v
Vagrant 2.0.0
```

### System configuration
**OS/Distro version:**:
Debian Stretch

**Libvirt version:**
3.0.0-4 (Distro package)

**Output of `vagrant version; vagrant plugin list`:**
```
Installed Version: 2.0.0
Latest Version: 2.0.0
 
You're running an up-to-date version of Vagrant!
vagrant-libvirt (0.0.40)
  - Version Constraint: > 0
vagrant-managed-servers (0.8.0)
  - Version Constraint: > 0
vagrant-share (1.1.9, system)
  - Version Constraint: > 0
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**

https://gist.github.com/kivoli/fae9019c8612e9e50e9f697da94e2983

Note: Removed `VAGRANT_OLD_*` and identifying information from output.

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
# vim: ft=ruby:sw=2:ts=2:ss=2:expandtab

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "debian/stretch64"
  config.vm.network 'forwarded_port', host: 6666, guest: 6666, protocol: 'udp'
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by infernix** [comment] 2017-11-23 14:13
Duplicate of #260

**Closed by infernix** 2017-11-23 14:13 UTC
