### ISSUE TITLE
connect_via_ssh does not work if I manually set the uri

### ISSUE THREAD

**Issue by dustymabe** [vagrant-libvirt/vagrant-libvirt#763] opened 2017-04-17 14:17 UTC
This may not be a bug, but it is definitely not obvious from the documentation and should be clarified if so. 

When I manually set the URI to connect over ssh to a remote libvirt host then `connect_via_ssh = true` does not work and bringing the machine up fails because vagrant can't ssh in. 

### Steps to reproduce
1. set uri to something like: `uri=qemu+ssh://dustymabe@192.168.X.XXX/system`
2. set `connect_via_ssh = true`
3. observe failure

### System configuration
**OS/Distro version:**
Fedora 25 - vagrant-libvirt-0.0.35-3.fc25.noarch

**Libvirt version:**
libvirt-daemon-2.2.0-2.fc25.x86_64

**Output of `vagrant version; vagrant plugin list`:**
$ vagrant version
Installed Version: 1.8.5
Latest Version: 1.9.3

**Comment by electrofelix** [comment] 2017-04-19 10:04
Looks like the problems is that while the code can build `@uri` from the individual settings, it doesn't support de-constructing a provided `@uri` into the component parts.

Can you confirm that setting the individual pieces used to construct the `@uri` work? Just like to confirm that is the problem.

**Comment by dustymabe** [comment] 2017-04-19 14:34
> Looks like the problems is that while the code can build @uri from the individual settings, it doesn't support de-constructing a provided @uri into the component parts.

yes, that is what I expected is the issue. 

> 
> Can you confirm that setting the individual pieces used to construct the @uri work? Just like to confirm that is the problem.

yes, i was able to workaround the problem the other day by specifying the different parts of the uri individually to the other options.

**Comment by itisnotdone** [comment] 2017-04-21 00:10
For me, using 'uri' setting works fine. I think you should probably check debug log using --debug option.
What you should see on the debug log will look like this.
"INFO driver: Connecting to Libvirt (qemu+ssh://USER@IP_OR_DOMAIN/system) ..."

**Comment by infernix** [comment] 2017-08-03 17:11
Please provide the required information asked when creating an isssue.

**Comment by dustymabe** [comment] 2017-08-03 18:58
> Please provide the required information asked when creating an isssue.

I guess I was thinking from the details I gave that it would be pretty easy to reproduce. I'll try to get the rest of the information for you, but if there is something specific you want I might be able to get that to you faster.

**Comment by infernix** [comment] 2017-08-05 16:39
With infinite free time everything can be reproduced ;) so please provide a debug log, thanks.

**Comment by electrofelix** [comment] 2021-03-22 12:03
Should be fixed by #1225

**Closed by electrofelix** 2021-03-22 12:03 UTC
Labels: needinfo, question
