### ISSUE TITLE
[Request]: Easy way to add plugin to docker image

### ISSUE THREAD

**Issue by hansbogert** [vagrant-libvirt/vagrant-libvirt#1212] opened 2021-03-04 13:03 UTC
Is there an easy way too extend/add a plugin to the docker image -- currently I have to copy this whole repo and just rebuild the whole image for just an extra plugin.

I'd hope I could've created a simple local Dockerfile which simply does 

`FROM vagrant-libvirt/vagrant-libvirt`

Alas, it's never that simple, because now I miss a lot of development dependencies, and there's also issues with the `/vagrant` folder

```Dockerfile
FROM vagrantlibvirt/vagrant-libvirt

RUN vagrant plugin install vagrant-winrm-syncedfolders
```

```bash
docker build .
Sending build context to Docker daemon  273.4kB
Step 1/2 : FROM vagrantlibvirt/vagrant-libvirt
 ---> 91d0d368d930
Step 2/2 : RUN vagrant plugin install vagrant-winrm-syncedfolders
 ---> Running in 2c4e362b5c9a
/opt/vagrant/embedded/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir': File exists @ dir_s_mkdir - /vagrant/boxes (Errno::EEXIST)
	from /opt/vagrant/embedded/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/fileutils.rb:200:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
	from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:823:in `block in setup_home_path'
	from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:818:in `each'
	from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:818:in `setup_home_path'
	from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:135:in `initialize'
	from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/bin/vagrant:168:in `new'
	from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/bin/vagrant:168:in `<main>'
The command '/bin/sh -c vagrant plugin install vagrant-winrm-syncedfolders' returned a non-zero code: 1

```

**Comment by electrofelix** [comment] 2021-03-20 16:58
I think there are a couple of options here:
1) try to have vagrant-libvirt installed so that it's automatically picked up by vagrant without needing to be under the `VAGRANT_HOME` directory
2) provide a guide for those extending to be set up and remove the directories needed to allow the plugin install
3) modify the existing image to not remove the directories and replace with symlinks and change the entrypoint script to handle this instead

I'll have a look at number one, and if that doesn't work, I'll see how 3 works out.

In the mean time something like the following should work (untested):
```
FROM vagrantlibvirt/vagrant-libvirt as build

RUN for dir in boxes data tmp; \
    do \
        mkdir /vagrant/${dir}; \
    done \
    vagrant plugin install vagrant-winrm-syncedfolders \
    do \
        rm -rf /vagrant/${dir}; \
    done \
    ;
```

**Comment by electrofelix** [comment] 2021-03-23 15:53
Looks like it's actually more complex and there is an issue caused by a mistake in my assumption about how the plugin install mechanism works in vagrant. I think this is ultimately a duplicate of #1198, so I'm going to close this one and continue the work in the original.

**Closed by electrofelix** 2021-03-23 15:53 UTC
