### ISSUE TITLE
Fix usage/warning of not set identity file

### ISSUE THREAD

**Issue by ElArtista** [vagrant-libvirt/vagrant-libvirt#1228] opened 2021-03-17 19:25 UTC
After latest changes in regarding group of PRs #1218, #1222, #1223, #1224 changes must be made to redirect port options here: https://github.com/vagrant-libvirt/vagrant-libvirt/blob/d4d82d977309895644622ddea35bb3ed23399edb/lib/vagrant-libvirt/action/forward_ports.rb#L107 to avoid following warning:

```
Warning: Identity file /home/theartist/.ssh/id_rsa not accessible: No such file or directory.
```

**Comment by electrofelix** [comment] 2021-03-17 22:27
I'm not sure that is the source of the warning you are seeing, I'm guessing I've made a mistake in setting up the defaults by not checking to see if the file exists, and it's the ssh proxy command that is resulting in this message. Because the contents of the hash here should actually be the private key used to access the VM itself.

If I run the latest master with the following Vagrantfile:
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora32"
  config.vm.network "forwarded_port", guest: 80, host: 8080
end
```

and I stick a `puts` in to output the contents of the hash referenced I see the following:
```
==> default: 80 (guest) => 8080 (host) (adapter eth0)
private_key_path=["/home/dara/git/github.com/vagrant-libvirt/vagrant-libvirt/.vagrant/machines/default/libvirt/private_key"]
```

So I suspect the problem is with how the proxy command is getting populated, and that might be partially fixed with #1226, just need to ensure the connect_via_ssh for the port forwards is also replaced with checking the proxy_command config setting.

**Comment by ElArtista** [comment] 2021-03-18 14:59
I think it comes from setting the IdentityFile option as I showed, when I do not provide any identity file at all in vagrant (I get them from the ssh-agent session)

**Comment by electrofelix** [comment] 2021-03-18 16:27
@ElArtista Can you describe your setup, because that IdentityFile is the vagrant machine private key that is used to access the VM itself, rather than the key used to access the machine that libvirt is running on.

Essentially it can only be skipped if some of the advanced ssh settings in https://www.vagrantup.com/docs/vagrantfile/ssh_settings#available-settings are enabled to switch to password connections and disable the key insertion.

A couple of lines below there is:
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/d4d82d977309895644622ddea35bb3ed23399edb/lib/vagrant-libvirt/action/forward_ports.rb#L110

The proxy_command could easily end up with a stray identify file left by default depending on how things are resolved, and as the entry that is added to proxy_command would typically default to `${HOME}/.ssh/id_rsa`, compared to the vagrant machine which will store the key in the `.vagrant` directory at the same level as the Vagrantfile just run, it seems a more likely culprit.

Have a look at #1226 which is looking at moving the proxy_command construction to be a config option, as it might solve the problem or, it may mean need additional work. With that PR I can add a check to see if the file exists as well, but if the file exists setting `id_ssh_key_file` to nil might be required to disable trying to pick it up at all and allow everything to be managed from ssh config.

**Comment by ElArtista** [comment] 2021-03-18 18:33
Seems that the warning popups even when halting the VMs!
```
vagrant halt
==> k3s-worker-02: Halting domain...
Warning: Identity file /home/theartist/.ssh/id_rsa not accessible: No such file or directory.
==> k3s-worker-01: Halting domain...
Warning: Identity file /home/theartist/.ssh/id_rsa not accessible: No such file or directory.
==> k3s-master-01: Halting domain...
Warning: Identity file /home/theartist/.ssh/id_rsa not accessible: No such file or directory.
```

My setup is pretty simple, just a remote beefy PC accessed with:
```
export VAGRANT_DEFAULT_PROVIDER=libvirt
export LIBVIRT_DEFAULT_URI="qemu+ssh://beefy/system"
```

And I'm using this vagrant file (minus the `lv.connect_via_ssh = true` after now after the latest commits)
https://github.com/ElArtista/kubelab/blob/0a02c7613e7761b192c19854ade22eaecc32e70c/Vagrantfile

**Comment by electrofelix** [comment] 2021-03-20 15:11
@ElArtista I think #1230 should fix the issue you are seeing by performing a simple check on whether the default ssh key exists. This way it should be set to nil before being attempted to be used in the proxy command. I've split this out from the other work on trying to auto enable connect_via_ssh if the provided uri contains ssh to try an ensure some consistency between setting individual options versus setting the uri explicitly and letting the code extract the used values from it.

**Closed** 2021-03-20 15:38 UTC
