### ISSUE TITLE
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.

### ISSUE THREAD

**Issue by mrgiles** [vagrant-libvirt/vagrant-libvirt#706] opened 2016-12-10 00:57 UTC
### Steps to reproduce
1. updated vagrant to latest available version
2. run vagrant status

### Expected behaviour
Tell us what should happen
Vagran still works but gives below warning message...
### Actual behaviour
Tell us what happens instead
Get following warning message:
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
### System configuration
**OS/Distro version:**:
Fedora 24
**Libvirt version:**
libvirt-1.3.3.2-1.fc24
**Output of `vagrant version; vagrant plugin list`:**
Vagrant Version: 1.9.1
Plugin version: vagrant-libvirt (0.0.36)
Gem version: ruby-libvirt (0.7.0)
**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by fowlslegs** [comment] 2016-12-13 22:49
Have this same problem on Debian sid. Using upstream-provided Vagrant 1.9.1 and distro-provided libvirt 2.4.0. Installed vagrant-libvirt following your README instructions. `gem pristine ruby-libvirt --version 0.7.0` succeeds, but does not resolve the error.

**Comment by devtosystems** [comment] 2016-12-16 21:04
I can't install ruby-libvirt or other dependence in my Debian 8 Jessie.

I follow the topic "Possible problems with plugin installation on linux" but not talk about problem to install dependencies.

https://github.com/vagrant-libvirt/vagrant-libvirt#possible-problems-with-plugin-installation-on-linux

```bash
make "DESTDIR="
compiling secret.c
secret.c:23:29: fatal error: libvirt/libvirt.h: No such file or directory
 #include <libvirt/libvirt.h>
                             ^
compilation terminated.
Makefile:237: recipe for target 'secret.o' failed
make: *** [secret.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/tosystems/.vagrant.d/gems/2.2.5/gems/ruby-libvirt-0.7.0 for inspection.
Results logged to /home/tosystems/.vagrant.d/gems/2.2.5/extensions/x86_64-linux/2.2.0/ruby-libvirt-0.7.0/gem_make.out
```

**Comment by infernix** [comment] 2016-12-16 21:15
@devtosystems few lines above.
See  https://github.com/vagrant-libvirt/vagrant-libvirt#installation "Ubuntu 12.04/14.04/16.04, Debian"

**Comment by devtosystems** [comment] 2016-12-16 21:26
I try this before but I'm not succeeded.
Each dependence need's other.

```bash
 sudo apt install ruby-libvirt 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ruby-libvirt : Depends: libvirt0 (>= 1.1.3~rc1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

and so on...

**Comment by eoli3n** [comment] 2017-01-10 07:40
Same here : 
```
 ⚡ root@server  ~/project/Vagrant/server-modulone   master  vagrant status
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
Current machine states:

default                   running (libvirt)

The Libvirt domain is running. To stop this machine, you can run
`vagrant halt`. To destroy the machine, you can run `vagrant destroy`.
 ⚡ root@server  ~/project/Vagrant/server-modulone   master  apt-get build-dep vagrant ruby-libvirt
Lecture des listes de paquets... Fait
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
0 mis à jour, 0 nouvellement installés, 0 à enlever et 13 non mis à jour.
 ⚡ root@server  ~/project/Vagrant/server-modulone   master  apt-get install qemu libvirt-bin ebtables dnsmasq
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Aucune version du paquet libvirt-bin n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source
Cependant les paquets suivants le remplacent :
  libvirt-daemon-system libvirt-dev libvirt-clients

E: Le paquet « libvirt-bin » n'a pas de version susceptible d'être installée
 ✘ ⚡ root@server  ~/project/Vagrant/server-modulone   master  apt-get install libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Note : sélection de « libxslt1-dev » au lieu de « libxslt-dev »
libvirt-dev is already the newest version (2.4.0-3).
libxml2-dev is already the newest version (2.9.4+dfsg1-2.1).
libxslt1-dev is already the newest version (1.1.29-2).
ruby-dev is already the newest version (1:2.3.3).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-4).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 13 non mis à jour.
 ⚡ root@server  ~/project/Vagrant/server-modulone   master  vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Installed the plugin 'vagrant-libvirt (0.0.36)'!
 ⚡ root@server  ~/project/Vagrant/server-modulone   master  gem pristine ruby-libvirt --version 0.7.0
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
Restored ruby-libvirt-0.7.0
 ⚡ root@server  ~/project/Vagrant/server-modulone   master  vagrant status                                   
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
Current machine states:

default                   running (libvirt)

The Libvirt domain is running. To stop this machine, you can run
`vagrant halt`. To destroy the machine, you can run `vagrant destroy`.

```

**Comment by linuxsimba** [comment] 2017-01-11 03:18
For some reason vagrant 1.9 has messed up libraries for ubuntu 16.04. installed vagrant-libvirt 0.0.37 with no issues using vagrant 1.8.7

**Comment by chrisspen** [comment] 2017-01-17 22:24
Does anyone have a workaround for this? Running the gem command fails on Ubuntu 16 with:

    $ gem pristine ruby-libvirt --version 0.7.0
    ERROR:  While executing gem ... (Gem::Exception)
        Failed to find gems ["ruby-libvirt"] = 0.7.0

There's a ruby-libvirt package in the standard repo, but it seems to have no effect, because even with that installed, `vagrant up --provider=libvirt` still says it's ignoring the extensions.

**Comment by gbritton** [comment] 2017-02-23 02:14
I see the vagrant-libvirt plugin has built this:
`.vagrant.d/gems/2.2.5/extensions/x86_64-linux/2.2.0/ruby-libvirt-0.7.0/gem.build_complete
`

But, when running vagrant, it's looking for this:
`.vagrant.d/gems/2.2.5/gems/extensions/x86_64-linux/2.2.0/ruby-libvirt-0.7.0/gem.build_complete
`

Note the extra "gems" directory under the 2.2.5 directory.

I do not know where this issue actually is, but I hope this find is useful in fixing this.

BTW, this works as a workaround, but is obviously not a real fix:
`ln -s ../extensions .vagrant.d/gems/2.2.5/gems
`

For completeness of this info, I'm installing the vagrant 1.9.1 RPM on CentOS 7 and using 0.0.37 via just "`vagrant plugin install vagrant-libvirt`"

**Comment by ekohl** [comment] 2017-02-23 09:19
I can confirm the workaround provided by @gbritton works on Gentoo as well.

**Comment by infernix** [comment] 2017-08-03 17:24
Please retest this with 1.9.7, it is likely fixed.

**Comment by duane** [comment] 2017-09-27 21:11
Confirmed @gbritton fix works as well on mac os.

**Comment by xenithorb** [comment] 2017-10-21 17:01
I'm not seeing this anymore on Fedora 27, so I think it can be closed.

**Comment by infernix** [comment] 2017-11-23 14:31
Closing this then, pease free to update or reopen this ticket if required. Thanks!

**Closed by infernix** 2017-11-23 14:31 UTC
Labels: bug

**Comment by TheCapsLock** [comment] 2026-02-10 09:01
A radical solution (only if you do not use ruby for anything else and you want to move fast):

```shell
rm -Rf ~/.gem/ruby
```

Then the plugin can be reinstalled:

```shell
vagrant plugin install vagrant-libvirt
```
