### ISSUE TITLE
Installation inside Docker

### ISSUE THREAD

**Issue by lukechilds** [vagrant-libvirt/vagrant-libvirt#1128] opened 2020-07-10 01:37 UTC
I'm trying to use `vagrant-libvirt` to create a portable containerised Vagrant setup. So Vagrant can be run anywhere that Docker is installed, regardless of host OS and without requiring Vagrant/VirtualBox installed on the host.

I'm doing this by installing Vagrant, QEMU and `vagrant-libvirt` inside a Debian based Docker container, then trying to run a Vagrantfile with the QEMU (not KVM) libvirt driver.

This is my Dockerfile:

```Dockerfile
FROM debian:buster-slim

# Update package lists
RUN apt-get update

# Install Vagrant
RUN apt-get install -y curl
RUN curl -O https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb
RUN apt-get install ./vagrant_2.2.6_x86_64.deb

# Install vagrant-libvirt
RUN apt-get install -y qemu qemu-utils libvirt-daemon-system libvirt-clients ebtables dnsmasq-base
RUN apt-get install -y libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev build-essential
RUN vagrant plugin install vagrant-libvirt

# Test vagrant up
RUN vagrant box add --provider libvirt debian/buster64
RUN echo '\n\
Vagrant.configure(2) do |config|\n\
  config.vm.box = "debian/buster64"\n\
  config.vm.provider :libvirt do |libvirt|\n\
    libvirt.driver = "qemu"\n\
  end\n\
end\n\
' > Vagrantfile
RUN libvirtd --daemon && vagrant up --provider=libvirt
```

The final step fails with:

```
Step 12/12 : RUN libvirtd --daemon && vagrant up --provider=libvirt
 ---> Running in 0244ad98b8e6
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'debian/buster64' version '10.4.0' is up to date...
==> default: Uploading base box image as volume into Libvirt storage...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              _default
==> default:  -- Domain type:       qemu
==> default:  -- Cpus:              1
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Memory:            512M
==> default:  -- Management MAC:
==> default:  -- Loader:
==> default:  -- Nvram:
==> default:  -- Base box:          debian/buster64
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/_default.img (20G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:
==> default:  -- Initrd:
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Sound Type:
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:
==> default:  -- INPUT:             type=mouse, bus=ps2
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: invalid argument: could not find capabilities for domaintype=qemu
The command '/bin/sh -c libvirtd --daemon && vagrant up --provider=libvirt' returned a non-zero code: 1
```

According to the [wiki](https://github.com/vagrant-libvirt/vagrant-libvirt/wiki#could-not-find-capabilities-for-domaintypekvm-or-domaintypeqemu), this suggests there is something wrong with my QEMU install. Do you have any suggestions as to what else I need to setup to get QEMU working?

If it's helpful, this is the output of `virsh capabilities` on the container:

<details>
  <summary>Click to open.</summary>

```xml
<capabilities>

  <host>
    <uuid>7f21418c-0000-0000-99bb-ae35069c9341</uuid>
    <cpu>
      <arch>x86_64</arch>
      <model>Westmere</model>
      <vendor>Intel</vendor>
      <topology sockets='6' cores='1' threads='1'/>
      <feature name='vme'/>
      <feature name='ss'/>
      <feature name='ht'/>
      <feature name='pbe'/>
      <feature name='pclmuldq'/>
      <feature name='dtes64'/>
      <feature name='ds_cpl'/>
      <feature name='fma'/>
      <feature name='xtpr'/>
      <feature name='pcid'/>
      <feature name='movbe'/>
      <feature name='xsave'/>
      <feature name='osxsave'/>
      <feature name='avx'/>
      <feature name='f16c'/>
      <feature name='rdrand'/>
      <feature name='hypervisor'/>
      <feature name='arat'/>
      <feature name='fsgsbase'/>
      <feature name='bmi1'/>
      <feature name='hle'/>
      <feature name='avx2'/>
      <feature name='bmi2'/>
      <feature name='erms'/>
      <feature name='rtm'/>
      <feature name='xsaveopt'/>
      <feature name='pdpe1gb'/>
      <feature name='abm'/>
      <feature name='3dnowprefetch'/>
      <feature name='invtsc'/>
      <pages unit='KiB' size='4'/>
      <pages unit='KiB' size='2048'/>
      <pages unit='KiB' size='1048576'/>
    </cpu>
    <power_management/>
    <iommu support='no'/>
    <migration_features>
      <live/>
      <uri_transports>
        <uri_transport>tcp</uri_transport>
        <uri_transport>rdma</uri_transport>
      </uri_transports>
    </migration_features>
    <cache>
      <bank id='0' level='3' type='both' size='8' unit='MiB' cpus='0'/>
      <bank id='1' level='3' type='both' size='8' unit='MiB' cpus='1'/>
      <bank id='2' level='3' type='both' size='8' unit='MiB' cpus='2'/>
      <bank id='3' level='3' type='both' size='8' unit='MiB' cpus='3'/>
      <bank id='4' level='3' type='both' size='8' unit='MiB' cpus='4'/>
      <bank id='5' level='3' type='both' size='8' unit='MiB' cpus='5'/>
    </cache>
    <secmodel>
      <model>none</model>
      <doi>0</doi>
    </secmodel>
    <secmodel>
      <model>dac</model>
      <doi>0</doi>
      <baselabel type='kvm'>+64055:+64055</baselabel>
      <baselabel type='qemu'>+64055:+64055</baselabel>
    </secmodel>
  </host>

</capabilities>
```

</details>

Thanks!

**Comment by electrofelix** [comment] 2020-07-17 10:05
The problem is that during a docker build the container doesn't have access the host devices that provide the ability for virtualization. What I think you want to do is put just libvirt + vagrant + vagrant-libvirt in a container. And at runtime mount in the /var/run/libvirt/libvirt-sock socket under the same path along with ~/.vagrant.d and the current directory containing your Vagrantifle allowing passing `vagrant up` as the runtime command.

However you'll also need an entrypoint to create a user at docker run time that is set to the same uid/gid as the ~/.vagrant.d folder mounted in, and is in the correct group to access the file /var/run/libvirt/libvirt-sock before switching to that user to execute the passed in CMD

e.g. Dockerfile
```
FROM debian:buster-slim as downloader

# Update package lists
RUN apt-get update

# Install Vagrant
RUN apt-get install -y curl
RUN curl -O https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb

FROM debian:buster-slim

RUN apt-get update \
    && apt-get install -y ./vagrant_2.2.6_x86_64.deb \ 
    && qemu qemu-utils libvirt-daemon-system libvirt-clients ebtables dnsmasq-base \
    && libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev build-essential \
    && rm -rf /var/cache/apt/

RUN vagrant plugin install vagrant-libvirt

ENV VAGRANT_HOME=/.vagrant.d
```

Then at run time
```
docker run -it --rm -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock -v ~/.vagrant.d:/vagrant.d -v $(pwd):$(pwd) -w $(pwd) vagrant-libvirt:latest vagrant up
```

I'm pretty sure I'm forgetting some pieces like being able to set the env correctly so that the gems installed under ~/.vagrant.d are used from the image while the boxes are used from the local user environment mounted in.

The reason to use an entry point is to switch user from root is to be able to modify the groups inside the container as they may not align with the group ids assigned to the libvirt group on the host while avoiding vagrant as root inside the container as that would end up using root on the host as well and that causes a series of issues with file ownership.

**Comment by electrofelix** [comment] 2020-07-17 10:17
This also reminded me to share the Dockerfiles we built internally to solve this problem, I'll probably need to submit via our internal approval system so it might take 3-4 weeks to be able to release. In the mean time I'll see what I can answer/share on how we enabled it to run and if you can get a working version might be able to incorporate that sooner.

**Comment by lukechilds** [comment] 2020-07-17 13:26
Thanks @electrofelix, really appreciate that!

**Comment by electrofelix** [comment] 2020-07-17 15:28
The way we did it was to create a symlink from /.vagrant.d/boxes to a path /persistent-boxes and mount ~/.vagrant.d/boxes at runtime onto the path in the container:
```
docker run -it --rm \
    -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock \
    -v ~/.vagrant.d/boxes:/persistent-boxes \
    -v $(pwd):$(pwd) \
    -w $(pwd) \
    vagrant-libvirt:latest vagrant up
```

That allowed use of the user cached boxes. Seems the main reason we were mounting in /dev/kvm as well was for supporting use of packer to build custom images as well. So that's not needed unless you are using it as well.

Really just about permissions and group membership then

**Comment by buckaroogeek** [comment] 2020-07-17 21:30
@electrofelix - thanks for the write-up. I was wondering how to accomplish this also!

**Comment by lukechilds** [comment] 2020-07-18 02:25
Ahh, thanks for sharing your solution @electrofelix.

So this requires the installation of both libvirt and Vagrant on the host?

 The goal of my Docker container is to handle the Vagrant/libvirt/QEMU stuff inside the container so the only host dep required is Docker. Anyone with Docker installed should be able to run the container and get access to a Vagrant box without requiring Vagrant/libvirt/QEMU installed.

**Comment by electrofelix** [comment] 2020-07-18 09:14
@lukechilds it'll require libvirtd and docker on the host. Vagrant will only be in the container. The idea is the libvirt socket acts as the communication channel and as libvirt tends to support a certain amount of cross version compatibility as long as using one of the standard communication paths (e.g remote libvirt connection uris) it should allow for version drift between host and container. Though probably requires the daemon version is same or newer than what is in the container as the client in certain cases.

You might be able to move the libvirtd into the container as well, the limitation here is if there is already a libvirtd running I can't imagine they will play nice, it'll probably also require additional work around privileges as especially around where data is persisted onto the host system. Between network configs under /etc, run time generated files for dnsmasq/firewalls/apparmor/selinux, as well as storage pools, that might be very difficult to get right both with the image as well as the exact runtime command line for the image. Depends on how much is needed or/and how many privileges your comfortable having VMS created by this container will have to your host system.

**Comment by lukechilds** [comment] 2020-07-18 09:41
The idea is it would have zero access to the host machine, it's completely guarded off by Docker. Apart from maybe a shared folder which the user would specify with a Docker Volume.

So QEMU would handle all virtualisation which would be running inside the Docker container.

You can see an example of something similar in another project of mine: https://github.com/lukechilds/dockerpi

It virtualises a Pi like system with QEMU inside a Docker container, there is no need for anything installed on the host but Docker.

That is essentially what I'm trying to achieve here with Vagrant.

**Comment by electrofelix** [comment] 2020-10-03 09:56
@lukechilds just coming back to this, as I'm trying to put together a docker container for vagrant-libvirt to run provided libvirt is installed on the host.

I think if you allow for /dev/kvm to be mounted into the container, it should be possible to have libvirtd run inside the container. Likely the container would need to be started as root in a daemon mode. I think you'd have to leave it running to prevent the VMs from being shutdown by libvirt on service stop. Not sure how easy it would be to allow normal users to interact, but if running as root is alright in your case it might not be an issue.

**Comment by electrofelix** [comment] 2020-11-18 10:11
I'm assuming the needed answers have been gotten, so will close this, please ping if you need any further info,

**Closed by electrofelix** 2020-11-18 10:11 UTC
